// AUTO-GENERATED by build.py — do not edit manually
// Last built: 2026-04-18 19:40:35
// Total alerts: 88

const ALERTS = [
  {
    "id": "SOC341",
    "title": "Local Privilege Escalation via chroot CVE-2025-32463",
    "date": "2026-04-18",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1068",
      "T1611",
      "T1059-004",
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-04-18-soc341-local-privilege-escalation-via-chroot-cve-2025-32463/",
    "youtube": "https://www.youtube.com/watch?v=HDe7SCR_ETU"
  },
  {
    "id": "SOC343",
    "title": "SOC343 - WinRAR Zero-Day Path Traversal Vulnerability CVE\u20112025\u20118088",
    "date": "2026-04-17",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1574-002",
      "T1547-001",
      "T1083"
    ],
    "tags": [
      "phishing",
      "level2"
    ],
    "url": "/investigations/2026-04-17-soc343-winrar-zero-day-path-traversal-vulnerability-cve20258088/",
    "youtube": "https://www.youtube.com/watch?v=vcXbMtdGme4"
  },
  {
    "id": "SOC101",
    "title": "SOC101 - Phishing Mail Detected Event 24",
    "date": "2026-04-15",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [],
    "tags": [],
    "url": "/investigations/2026-04-15-soc101-phishing-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=RbRc1K-a6Og"
  },
  {
    "id": "SOC106",
    "title": "Found Suspicious File - TI Data",
    "date": "2026-04-14",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [],
    "tags": [],
    "url": "/investigations/2026-04-14-soc106-found-suspicious-file-ti-data/",
    "youtube": "https://www.youtube.com/watch?v=-A9x3R0V0b0"
  },
  {
    "id": "SOC101",
    "title": "Phishing Mail Detected Event 29",
    "date": "2026-04-13",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-04-13-soc101-phishing-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=kHKBA6JkeB4"
  },
  {
    "id": "SOC107",
    "title": "Privilege Escalation Detected Event 19",
    "date": "2026-04-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1068",
      "T1204-002",
      "T1566-001"
    ],
    "tags": [
      "phishing",
      "privesc"
    ],
    "url": "/investigations/2026-04-12-soc107-privilege-escalation-detected/",
    "youtube": "https://www.youtube.com/watch?v=nshjmOzdxEs"
  },
  {
    "id": "SOC104",
    "title": "Malware Detected Event 21",
    "date": "2026-04-11",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1240-002",
      "T1059-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "architecture"
    ],
    "url": "/investigations/2026-04-11-soc104-malware-detected/",
    "youtube": "https://www.youtube.com/watch?v=5Olw27bj6T8"
  },
  {
    "id": "SOC113",
    "title": "- Suspicious hh.exe Usage",
    "date": "2026-04-10",
    "platform": "letsdefend",
    "severity": "low",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [],
    "tags": [],
    "url": "/investigations/2026-04-10-soc113-suspicious-hhexe-usage/",
    "youtube": "https://www.youtube.com/watch?v=BaNDu0kKsvA"
  },
  {
    "id": "SOC101",
    "title": "SOC101 - Phishing Mail Detected Event 25",
    "date": "2026-04-09",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1059-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-04-09-soc101-phishing-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=AYIkPMy_brg"
  },
  {
    "id": "SOC101",
    "title": "Phishing Mail Detected",
    "date": "2026-04-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1059-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-04-08-soc101-phishing-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=9C3J5QxIOhk"
  },
  {
    "id": "SOC102",
    "title": "Proxy - Suspicious URL Detected",
    "date": "2026-04-07",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-07-soc102-proxy-suspicious-url-detected/",
    "youtube": "https://www.youtube.com/watch?v=S4qZ2K2cEzE"
  },
  {
    "id": "SOC121",
    "title": "Proxy - Malicious Executable File Detected event 79",
    "date": "2026-04-06",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-06-soc121-proxy-malicious-executable-file-detected/",
    "youtube": "https://www.youtube.com/watch?v=ZK5e98UmIHM"
  },
  {
    "id": "SOC132",
    "title": "Same Malicious File Found on Multiple Sources",
    "date": "2026-04-05",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059-003",
      "T1105",
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-05-soc132-same-malicious-file-found-on-multiple-sources/",
    "youtube": "https://www.youtube.com/watch?v=kjvK2DsdzZU"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected event 31",
    "date": "2026-04-05",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204-002",
      "T1105",
      "T1071-001",
      "T1041"
    ],
    "tags": [],
    "url": "/investigations/2026-04-05-soc104-malware-detected/",
    "youtube": "https://www.youtube.com/watch?v=DEJvjtvRTrI"
  },
  {
    "id": "SOC123",
    "title": "Enumeration Tool Detected",
    "date": "2026-04-04",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1082",
      "T1069",
      "T1083",
      "T1105",
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-04-soc123-enumeration-tool-detected/",
    "youtube": "https://www.youtube.com/watch?v=FdbET7tWpgk"
  },
  {
    "id": "SOC102",
    "title": "Proxy - Suspicious URL Detected event 32",
    "date": "2026-04-04",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-04-soc102-proxy-suspicious-url-detected-event-32/",
    "youtube": "https://www.youtube.com/watch?v=1PMK6j7896c"
  },
  {
    "id": "SOC102",
    "title": "Proxy - Suspicious URL Detected",
    "date": "2026-04-02",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059-001",
      "T1105",
      "T1027",
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-03-soc102-proxy-suspicious-url-detected/",
    "youtube": "https://www.youtube.com/watch?v=lonVO0NrCUQ"
  },
  {
    "id": "SOC109",
    "title": "SOC109 - Emotet Malware Detected",
    "date": "2026-04-02",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1059-001",
      "T1105",
      "T1071-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-02-soc109-emotet-malware-detected/",
    "youtube": "https://www.youtube.com/watch?v=meIPiFZLm-E"
  },
  {
    "id": "SOC133",
    "title": "Suspicious Request to New Registered Domain",
    "date": "2026-04-01",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1583-001"
    ],
    "tags": [],
    "url": "/investigations/2026-04-01-soc133-suspicious-request-to-new-registered-domain/",
    "youtube": "https://www.youtube.com/watch?v=ZI8eYRerTbU"
  },
  {
    "id": "SOC110",
    "title": "Proxy - Cryptojacking Detected",
    "date": "2026-03-31",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1071-001",
      "T1036"
    ],
    "tags": [],
    "url": "/investigations/2026-03-31-soc110-proxy-cryptojacking-detected/",
    "youtube": "https://www.youtube.com/watch?v=OBtvgBEQi9I"
  },
  {
    "id": "SOC115",
    "title": "Wscript.exe Usage as Dropper",
    "date": "2026-03-30",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1218-005",
      "T1105",
      "T1071-001",
      "T1027",
      "T1046"
    ],
    "tags": [
      "LOLBin"
    ],
    "url": "/investigations/2026-03-30-soc113-wscriptexe-usage-as-dropper/",
    "youtube": "https://www.youtube.com/watch?v=-Hb5Nyo6zbU"
  },
  {
    "id": "SOC111",
    "title": "Traffic to Malware Domain event 42",
    "date": "2026-03-30",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059-001",
      "T1071-001",
      "T1053",
      "T1204-002"
    ],
    "tags": [],
    "url": "/investigations/2026-03-30-soc111-traffic-to-malware-domain-event42/",
    "youtube": "https://www.youtube.com/watch?v=01ywGuxTxGY"
  },
  {
    "id": "SOC112",
    "title": "Traffic to Blacklisted IP",
    "date": "2026-03-29",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204-002",
      "T1105",
      "T1059-001",
      "T1071-001",
      "T1027"
    ],
    "tags": [],
    "url": "/investigations/2026-03-29-soc112-traffic-to-blacklisted-ip/",
    "youtube": "https://www.youtube.com/watch?v=22GrGEWL_Iw"
  },
  {
    "id": "SOC111",
    "title": "Traffic to Malware Domain",
    "date": "2026-03-28",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1071",
      "T1105",
      "T1204"
    ],
    "tags": [],
    "url": "/investigations/2026-03-28-soc111-traffic-to-malware-domain/",
    "youtube": "https://www.youtube.com/watch?v=CKbyaH9P4Vc"
  },
  {
    "id": "SOC107",
    "title": "Privilege Escalation Detected",
    "date": "2026-03-27",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1068",
      "T1204",
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-03-27-soc107-privilege-escalation-detected/",
    "youtube": "https://www.youtube.com/watch?v=NOqKpjDGsjc"
  },
  {
    "id": "SOC135",
    "title": "Multiple FTP Connection Attempt",
    "date": "2026-03-26",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [],
    "tags": [],
    "url": "/investigations/2026-03-26-soc135-multiple-ftp-connection-attempt/",
    "youtube": "https://www.youtube.com/watch?v=8P7Ofu4yOu4"
  },
  {
    "id": "SOC119",
    "title": "Proxy - Malicious Executable File Detected event 79",
    "date": "2026-03-25",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-03-25-soc119-proxy-malicious-executable-file-detected-event-79/",
    "youtube": "https://www.youtube.com/watch?v=gk9CzLM3NEs"
  },
  {
    "id": "SOC116",
    "title": "DNS Hijacking Detected",
    "date": "2026-03-23",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1565-001",
      "T1546-008",
      "T1036"
    ],
    "tags": [
      "dnshijack"
    ],
    "url": "/investigations/2026-03-23-soc116-dns-hijacking-detected/",
    "youtube": "https://www.youtube.com/watch?v=GZ68RZ-BWZ0"
  },
  {
    "id": "SOC124",
    "title": "SOC144 - New scheduled task created",
    "date": "2026-03-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1053-005"
    ],
    "tags": [],
    "url": "/investigations/2026-03-22-soc124-scheduled-task-created/",
    "youtube": "https://www.youtube.com/watch?v=xcPDt4EsI8M"
  },
  {
    "id": "SOC108",
    "title": "Malicious Remote Access Software Detected",
    "date": "2026-03-21",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1219"
    ],
    "tags": [],
    "url": "/investigations/2026-03-21-soc108-malicious-remote-access-software-detected/",
    "youtube": "https://www.youtube.com/watch?v=nCWnN5enrmo"
  },
  {
    "id": "SOC101",
    "title": "Phishing Mail Detected",
    "date": "2026-03-20",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-002",
      "T1204"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-03-20-soc101-phishing-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=xQyj9NqCf-o"
  },
  {
    "id": "SOC127e60",
    "title": "SQL Injection Detected event 60",
    "date": "2026-03-19",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1190",
      "T1059"
    ],
    "tags": [],
    "url": "/investigations/2026-03-19-soc127-sql-injection-detected-event-60/",
    "youtube": "https://www.youtube.com/watch?v=Zi-NlBVcSKY"
  },
  {
    "id": "SOC235",
    "title": "Confluence Broken Access Control 0-Day CVE-2023-22515",
    "date": "2026-09-18",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1078",
      "T1136"
    ],
    "tags": [],
    "url": "/investigations/2026-03-18-soc235-atlassian-confluence-broken-access-control-0-day-cve-2023-22515/",
    "youtube": "https://www.youtube.com/watch?v=ZPfoIJKxjM0"
  },
  {
    "id": "SOC125",
    "title": "Suspicious Rundll32 Activity",
    "date": "2026-03-17",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1218-011",
      "T1566-002",
      "T1105",
      "T1071"
    ],
    "tags": [
      "emotet"
    ],
    "url": "/investigations/2026-03-17-soc125-suspicious-rundll32-activity/",
    "youtube": "https://www.youtube.com/watch?v=-TtRQU3s5Vg"
  },
  {
    "id": "SOC153",
    "title": "Suspicious Powershell Script Executed",
    "date": "2026-03-16",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059-001",
      "T1105",
      "T1071"
    ],
    "tags": [
      "powershell"
    ],
    "url": "/investigations/2026-03-16-soc153-suspicious-powershell-script-executed/",
    "youtube": "https://www.youtube.com/watch?v=chlNqbtBWnk"
  },
  {
    "id": "SOC126",
    "title": "Suspicious New Autorun Value Detected",
    "date": "2026-03-15",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1547",
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-03-15-soc126-suspicious-new-autorun-value-detected/",
    "youtube": "https://www.youtube.com/watch?v=GGnWsMwyLwQ"
  },
  {
    "id": "SOC136",
    "title": "Data Leak via Mailbox Forwarding Detected",
    "date": "2026-03-14",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1567",
      "T114"
    ],
    "tags": [
      "data-exfil"
    ],
    "url": "/investigations/2026-03-14-soc136-data-leak-via-mailbox-forwarding-detected/",
    "youtube": "https://www.youtube.com/watch?v=KIhPosT3u7w"
  },
  {
    "id": "SOC128",
    "title": "Malicious File Upload Attempt",
    "date": "2026-03-13",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1505-003",
      "T1059"
    ],
    "tags": [
      "webshell",
      "RCE"
    ],
    "url": "/investigations/2026-03-13-soc128-malicious-file-upload-attempt/",
    "youtube": "https://www.youtube.com/watch?v=Ph_4qwzCcZA"
  },
  {
    "id": "SOC129",
    "title": "Successful Local File Inclusion",
    "date": "2026-03-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1006"
    ],
    "tags": [
      "LFI"
    ],
    "url": "/investigations/2026-03-12-soc129-successful-local-file-inclusion/",
    "youtube": "https://www.youtube.com/watch?v=9C3J5QxIOhk"
  },
  {
    "id": "SOC130",
    "title": "Event Log Cleared",
    "date": "2026-03-11",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1070"
    ],
    "tags": [],
    "url": "/investigations/2026-03-11-soc130-event-log-cleared/",
    "youtube": "https://www.youtube.com/watch?v=KoEhkdWi8og"
  },
  {
    "id": "SOC147",
    "title": "SSH Scan Activity",
    "date": "2026-03-10",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1046"
    ],
    "tags": [
      "nmap"
    ],
    "url": "/investigations/2026-03-10-soc147-ssh-scan-activity/",
    "youtube": "https://www.youtube.com/watch?v=voqNx10QUy4"
  },
  {
    "id": "SOC139",
    "title": "Meterpreter or Empire Activity",
    "date": "2026-03-08",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "cobaltstrike"
    ],
    "url": "/investigations/2026-03-08-soc139-meterpreter-or-empire-activity/",
    "youtube": "https://www.youtube.com/watch?v=9xnJ_2gDDe8"
  },
  {
    "id": "SOC102",
    "title": "Proxy - Suspicious URL Detected",
    "date": "2026-03-08",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1071"
    ],
    "tags": [],
    "url": "/investigations/2026-03-08-soc102-proxy-suspicious-url-detected/",
    "youtube": "https://www.youtube.com/watch?v=a3YLgVEd-yg"
  },
  {
    "id": "SOC131",
    "title": "Reverse TCP Backdoor Detected",
    "date": "2026-03-06",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059-003",
      "T1059-006"
    ],
    "tags": [
      "revshell"
    ],
    "url": "/investigations/2026-03-06-soc131-reverse-tcp-backdoor-detected/",
    "youtube": "https://www.youtube.com/watch?v=GiClVeUY7Qc"
  },
  {
    "id": "SOC246",
    "title": "Forced Authentication Detected event 208",
    "date": "2026-03-05",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1105",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-03-05-soc246-forced-authentication-detected-event-208/",
    "youtube": "https://www.youtube.com/watch?v=YCC3rYv0UIM"
  },
  {
    "id": "SOC134_id71",
    "title": "Suspicious WMI Activity event 71",
    "date": "2026-03-04",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1047",
      "T1021-002",
      "T1059",
      "T1041"
    ],
    "tags": [
      "WMI"
    ],
    "url": "/investigations/2026-03-04-soc134-suspicious-wmi-activity-event-id-71/",
    "youtube": "https://www.youtube.com/watch?v=J8puwgZFgHM"
  },
  {
    "id": "SOC202",
    "title": "FakeGPT Malicious Chrome Extension",
    "date": "2026-03-03",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1071-001",
      "T1557",
      "T1539",
      "T1041"
    ],
    "tags": [],
    "url": "/investigations/2026-03-03-soc202-fakegpt-malicious-chrome-extension/",
    "youtube": "https://www.youtube.com/watch?v=j97apnHGKmU"
  },
  {
    "id": "SOC142",
    "title": "Multiple HTTP 500 Response",
    "date": "2026-03-02",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1505-003",
      "T1059",
      "T1071-001"
    ],
    "tags": [
      "revshell",
      "sqli"
    ],
    "url": "/investigations/2026-03-02-soc142-multiple-http-500-response/",
    "youtube": "https://www.youtube.com/watch?v=Yn7bDAFPtEY"
  },
  {
    "id": "SOC163",
    "title": "Suspicious Certutil.exe Usage",
    "date": "2026-03-01",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1105",
      "T1218"
    ],
    "tags": [
      "LOLBin",
      "certutil"
    ],
    "url": "/investigations/2026-03-01-soc163-suspicious-certutilexe-usage/",
    "youtube": "https://www.youtube.com/watch?v=06CnROH8rVM"
  },
  {
    "id": "SOC205",
    "title": "Malicious Macro has been executed",
    "date": "2026-02-28",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204",
      "T1059-001",
      "T1105"
    ],
    "tags": [
      "phishing",
      "powershell"
    ],
    "url": "/investigations/2026-02-28-soc205-malicious-macro-has-been-executed/",
    "youtube": "https://www.youtube.com/watch?v=4YHuizOa60k"
  },
  {
    "id": "SOC134",
    "title": "Suspicious WMI Activity",
    "date": "2026-02-28",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1047",
      "T1204",
      "T1486",
      "T1059"
    ],
    "tags": [
      "WMI"
    ],
    "url": "/investigations/2026-02-28-soc134-suspicious-wmi-activity/",
    "youtube": "https://www.youtube.com/watch?v=W3o5tSyrK_s"
  },
  {
    "id": "SOC143",
    "title": "Password Stealer Detected",
    "date": "2026-02-27",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1056"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-27-soc143-password-stealer-detected/",
    "youtube": "https://www.youtube.com/watch?v=BS44B5w17KI"
  },
  {
    "id": "SOC239",
    "title": "Remote Code Execution Detected in Splunk Enterprise",
    "date": "2026-02-26",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059",
      "T1105",
      "T1136",
      "T1505-003"
    ],
    "tags": [
      "CVE-2023-46214"
    ],
    "url": "/investigations/2026-02-26-soc239-remote-code-execution-detected-in-splunk-enterprise/",
    "youtube": "https://www.youtube.com/watch?v=yUexYuQlrVs"
  },
  {
    "id": "SOC287",
    "title": "Arbitrary File Read on Checkpoint Security Gateway [CVE-2024-24919]",
    "date": "2026-02-25",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1218-005"
    ],
    "tags": [],
    "url": "/investigations/2026-02-25-soc287-arbitrary-file-read-on-checkpoint-security-gateway-cve-2024-24919/",
    "youtube": "https://www.youtube.com/watch?v=fHAhEA-jKrY"
  },
  {
    "id": "SOC144",
    "title": "SOC144 - New scheduled task created",
    "date": "2026-02-24",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1053-005",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "persistance"
    ],
    "url": "/investigations/2026-02-24-soc144-new-scheduled-task-created/",
    "youtube": "https://www.youtube.com/watch?v=O_5Z0bZbGHc"
  },
  {
    "id": "SOC175",
    "title": "PowerShell Found in Requested URL - Possible CVE-2022-41082 Exploitation",
    "date": "2026-02-23",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059-001",
      "T1046"
    ],
    "tags": [
      "RCE"
    ],
    "url": "/investigations/2026-02-23-soc175-powershell-found-in-requested-url-possible-cve-2022-41082-exploitation/",
    "youtube": "https://www.youtube.com/watch?v=evstCoGR9nU"
  },
  {
    "id": "SOC173",
    "title": "Follina 0-Day Detected",
    "date": "2026-02-22",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204",
      "T1059-003",
      "T1203",
      "T1105",
      "T1218"
    ],
    "tags": [],
    "url": "/investigations/2026-02-22-soc173-follina-0-day-detected/",
    "youtube": "https://www.youtube.com/watch?v="
  },
  {
    "id": "SOC164",
    "title": "Suspicious Mshta Behavior",
    "date": "2026-02-21",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1218-005",
      "T1059-001",
      "T1105",
      "T1027"
    ],
    "tags": [
      "mshta"
    ],
    "url": "/investigations/2026-02-21-soc164-suspicious-mshta-behavior/",
    "youtube": "https://www.youtube.com/watch?v=DmN7Gg9VsYA"
  },
  {
    "id": "SOC282",
    "title": "SOC282 - Phishing Alert - Deceptive Mail Detected",
    "date": "2026-01-21",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1071-001",
      "T1105"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc282-phishing-alert-deceptive-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=t9YJ4-IAxdk"
  },
  {
    "id": "SOC227",
    "title": "SOC227 - Microsoft SharePoint Server Elevation of Privilege - Possible CVE-2023-29357 Exploitation",
    "date": "2026-02-20",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1068"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc227-microsoft-sharepoint-server-elevation-of-privilege-possible-cve-2023-29357-exploitation/",
    "youtube": "https://www.youtube.com/watch?v=PL8Uw6hs1Y4"
  },
  {
    "id": "SOC211",
    "title": "SOC211 - Utilman.exe Winlogon Exploit Attempt",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1546-008",
      "T1136",
      "T1068"
    ],
    "tags": [
      "LOLBin",
      "privesc"
    ],
    "url": "/investigations/2026-02-20-soc211-utilmanexe-winlogon-exploit-attempt/",
    "youtube": "https://www.youtube.com/watch?v=hpiJsYMw1aU"
  },
  {
    "id": "SOC169",
    "title": "SOC169 - Possible IDOR Attack Detected",
    "date": "2026-01-20",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1087"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc169-possible-idor-attack-detected/",
    "youtube": "https://www.youtube.com/watch?v=FNAWgTI8BOU"
  },
  {
    "id": "SOC140",
    "title": "SOC140 - Phishing Mail Detected - Suspicious Task Scheduler",
    "date": "2026-01-21",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1053"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc140-phishing-mail-detected-suspicious-task-scheduler/",
    "youtube": "https://www.youtube.com/watch?v=1lWhnfYLDDw"
  },
  {
    "id": "SOC119",
    "title": "SOC119 - Proxy - Malicious Executable File Detected",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1204"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc119-proxy-malicious-executable-file-detected/",
    "youtube": "https://www.youtube.com/watch?v=ad9d4YNMy_8"
  },
  {
    "id": "SOC114",
    "title": "SOC114 - Malicious Attachment Detected - Phishing",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1071-001"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc114-malicious-attachment-detected-phishing/",
    "youtube": "https://www.youtube.com/watch?v=4Iy8K7yG9qo"
  },
  {
    "id": "SOC109",
    "title": "SOC109 - Emotet Malware Detected",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1071-001",
      "T1105"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc109-emotet-malware-detected/",
    "youtube": "https://www.youtube.com/watch?v=rIWHgJJCtNk"
  },
  {
    "id": "SOC105",
    "title": "SOC105 - Requested T.I. URL address",
    "date": "2026-02-07",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1105"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc105-requested-ti-url-address/",
    "youtube": "https://www.youtube.com/watch?v=FjovKdW5zPQ"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected event 84",
    "date": "2026-01-23",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1204-002"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc104-malware-detected-event-84/",
    "youtube": "https://www.youtube.com/watch?v=wwaeV0Oq1dg"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected event 36",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204-002",
      "T1105",
      "T1071-001",
      "T1486"
    ],
    "tags": [
      "ransomware"
    ],
    "url": "/investigations/2026-02-20-soc104-malware-detected-event-36/",
    "youtube": "https://www.youtube.com/watch?v=xBDJH59D9JM"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected Event 14",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1204"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc104-malware-detected-event-14/",
    "youtube": "https://www.youtube.com/watch?v=hDOinM80634"
  },
  {
    "id": "SOC210",
    "title": "Possible Brute Force Detected on VPN",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1105",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-02-19-soc210-possible-brute-force-detected-on-vpn/",
    "youtube": "https://www.youtube.com/watch?v=LwI0ZEuL6M4"
  },
  {
    "id": "SOC275",
    "title": "Application Token Steal Attempt Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-002",
      "T1056",
      "T1078"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-18-soc275-application-token-steal-attempt-detected/",
    "youtube": "https://www.youtube.com/watch?v=Sr_fc_LakM0"
  },
  {
    "id": "SOC250",
    "title": "APT35 HyperScrape Data Exfiltration Tool Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1567",
      "T1041",
      "T1059",
      "T1078"
    ],
    "tags": [],
    "url": "/investigations/2026-02-18-soc250-apt35-hyperscrape-data-exfiltration-tool-detected/",
    "youtube": "https://www.youtube.com/watch?v=SNroeSufrG0"
  },
  {
    "id": "SOC336",
    "title": "Windows OLE Zero-Click RCE Exploitation Detected (CVE-2025-21298)",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1203",
      "T1218-010",
      "T1105",
      "T1059-003"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-17-soc336-windows-ole-zero-click-rce-exploitation-detected-cve-2025-21298/",
    "youtube": "https://www.youtube.com/watch?v=Vcn15XrdS1k"
  },
  {
    "id": "SOC251",
    "title": "Quishing Detected (QR Code Phishing)",
    "date": "2026-02-13",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1556",
      "T1566-001",
      "T1021-002",
      "T1036"
    ],
    "tags": [
      "quishing"
    ],
    "url": "/investigations/2026-02-13-soc251-quishing-detected-qr-code-phishing/",
    "youtube": "https://www.youtube.com/watch?v=Z5SHhAj90Tg"
  },
  {
    "id": "SOC342",
    "title": "CVE\u20112025\u201153770 SharePoint ToolShell Auth Bypass and RCE",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059-001",
      "T1505-003"
    ],
    "tags": [
      "sharepoint",
      "cve-2025-53770"
    ],
    "url": "/investigations/2026-02-12-soc342-cve202553770-sharepoint-toolshell-auth-bypass-and-rce/",
    "youtube": "https://www.youtube.com/watch?v=bzQCvhPa9FM"
  },
  {
    "id": "SOC338",
    "title": "Lumma Stealer - DLL Side-Loading via Click Fix Phishing",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1218",
      "T1059",
      "T1105"
    ],
    "tags": [
      "spearphishing"
    ],
    "url": "/investigations/2026-02-12-soc338-lumma-stealer-dll-side-loading-via-click-fix-phishing/",
    "youtube": "https://www.youtube.com/watch?v=9uLtQAU2Y84"
  },
  {
    "id": "SOC335",
    "title": "CVE-2024-49138 Exploitation Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1078",
      "T1021-002",
      "T1059",
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc335-cve-2024-49138-exploitation-detected/",
    "youtube": "https://www.youtube.com/watch?v=GuRlqUA7MnQ"
  },
  {
    "id": "SOC326",
    "title": "Impersonating Domain MX Record Change Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1584",
      "T1589",
      "T1598"
    ],
    "tags": [
      "phishing",
      "spearphishing"
    ],
    "url": "/investigations/2026-02-12-soc326-impersonating-domain-mx-record-change-detected/",
    "youtube": "https://www.youtube.com/watch?v=Oinrp7zOSAg"
  },
  {
    "id": "SOC274",
    "title": "Palo Alto Networks PAN-OS Command Injection Vulnerability Exploitation (CVE-2024-3400)",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059",
      "T1505-003"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc274-palo-alto-networks-pan-os-command-injection-vulnerability-exploitation-cve-2024-3400/",
    "youtube": "https://www.youtube.com/watch?v=XsIR3zQrtwk"
  },
  {
    "id": "SOC257",
    "title": "VPN Connection Detected from Unauthorized Country",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1078",
      "T1621"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc257-vpn-connection-detected-from-unauthorized-country/",
    "youtube": "https://www.youtube.com/watch?v=dl7SOIIB7Yc"
  },
  {
    "id": "SOC170",
    "title": "Passwd Found in Requested URL - Possible LFI Attack",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1006"
    ],
    "tags": [
      "LFI"
    ],
    "url": "/investigations/2026-02-12-soc170-passwd-found-in-requested-url-possible-lfi-attack/",
    "youtube": "https://www.youtube.com/watch?v=uW8-8uvZ9ws"
  },
  {
    "id": "SOC145",
    "title": "Ransomware Detected",
    "date": "2026-01-26",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1486",
      "T1490",
      "T1021-002"
    ],
    "tags": [
      "ransomware"
    ],
    "url": "/investigations/2026-02-12-soc145-ransomware-detected/",
    "youtube": "https://www.youtube.com/watch?v=aY5zmcRyrFw"
  },
  {
    "id": "SOC141",
    "title": "Phishing URL Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-12-soc141-phishing-url-detected/",
    "youtube": "https://www.youtube.com/watch?v=TCJv1ndeOiU"
  },
  {
    "id": "SOC138",
    "title": "Detected Suspicious Xls File",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1105"
    ],
    "tags": [
      "malware"
    ],
    "url": "/investigations/2026-02-12-soc138-detected-suspicious-xls-file/",
    "youtube": "https://www.youtube.com/watch?v=_v-r9R1n1bI"
  },
  {
    "id": "SOC176",
    "title": "RDP Brute Force Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1110",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-02-11-soc176-rdp-brute-force-detected/",
    "youtube": "https://www.youtube.com/watch?v=FpjV-H9zeFc"
  },
  {
    "id": "SOC127",
    "title": "SQL Injection Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059"
    ],
    "tags": [
      "sqli"
    ],
    "url": "/investigations/2026-02-11-soc127-sql-injection-detected/",
    "youtube": "https://www.youtube.com/watch?v=5tyD2HPAfDA"
  },
  {
    "id": "SOC137",
    "title": "Malicious File or Script Download Attempt",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059",
      "T1204-002"
    ],
    "tags": [
      "malware"
    ],
    "url": "/investigations/2026-02-08-soc137-malicious-file-or-script-download-attempt/",
    "youtube": "https://www.youtube.com/watch?v=fQUIvukK9qU"
  }
];
