// AUTO-GENERATED by build.py — do not edit manually
// Last built: 2026-02-20 21:04:24
// Total alerts: 19

const ALERTS = [
  {
    "id": "SOC227",
    "title": "SOC227 - Microsoft SharePoint Server Elevation of Privilege - Possible CVE-2023-29357 Exploitation",
    "date": "2026-02-20",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1068"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc227-microsoft-sharepoint-server-elevation-of-privilege-possible-cve-2023-29357-exploitation/"
  },
  {
    "id": "SOC210",
    "title": "Possible Brute Force Detected on VPN",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1105",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-02-19-soc210-possible-brute-force-detected-on-vpn/"
  },
  {
    "id": "SOC275",
    "title": "Application Token Steal Attempt Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-002",
      "T1056",
      "T1078"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-18-soc275-application-token-steal-attempt-detected/"
  },
  {
    "id": "SOC250",
    "title": "APT35 HyperScrape Data Exfiltration Tool Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1567",
      "T1041",
      "T1059",
      "T1078"
    ],
    "tags": [],
    "url": "/investigations/2026-02-18-soc250-apt35-hyperscrape-data-exfiltration-tool-detected/"
  },
  {
    "id": "SOC336",
    "title": "Windows OLE Zero-Click RCE Exploitation Detected (CVE-2025-21298)",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1203",
      "T1218-010",
      "T1105",
      "T1059-003"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-17-soc336-windows-ole-zero-click-rce-exploitation-detected-cve-2025-21298/"
  },
  {
    "id": "SOC251",
    "title": "Quishing Detected (QR Code Phishing)",
    "date": "2026-02-13",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1556",
      "T1566-001",
      "T1021-002",
      "T1036"
    ],
    "tags": [
      "quishing"
    ],
    "url": "/investigations/2026-02-13-soc251-quishing-detected-qr-code-phishing/"
  },
  {
    "id": "SOC342",
    "title": "CVE\u20112025\u201153770 SharePoint ToolShell Auth Bypass and RCE",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059-001",
      "T1505-003"
    ],
    "tags": [
      "sharepoint",
      "cve-2025-53770"
    ],
    "url": "/investigations/2026-02-12-soc342-cve202553770-sharepoint-toolshell-auth-bypass-and-rce/"
  },
  {
    "id": "SOC338",
    "title": "Lumma Stealer - DLL Side-Loading via Click Fix Phishing",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1218",
      "T1059",
      "T1105"
    ],
    "tags": [
      "spearphishing"
    ],
    "url": "/investigations/2026-02-12-soc338-lumma-stealer-dll-side-loading-via-click-fix-phishing/"
  },
  {
    "id": "SOC335",
    "title": "CVE-2024-49138 Exploitation Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1078",
      "T1021-002",
      "T1059",
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc335-cve-2024-49138-exploitation-detected/"
  },
  {
    "id": "SOC326",
    "title": "Impersonating Domain MX Record Change Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1584",
      "T1589",
      "T1598"
    ],
    "tags": [
      "phishing",
      "spearphishing"
    ],
    "url": "/investigations/2026-02-12-soc326-impersonating-domain-mx-record-change-detected/"
  },
  {
    "id": "SOC274",
    "title": "Palo Alto Networks PAN-OS Command Injection Vulnerability Exploitation (CVE-2024-3400)",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059",
      "T1505-003"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc274-palo-alto-networks-pan-os-command-injection-vulnerability-exploitation-cve-2024-3400/"
  },
  {
    "id": "SOC257",
    "title": "VPN Connection Detected from Unauthorized Country",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1078",
      "T1621"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc257-vpn-connection-detected-from-unauthorized-country/"
  },
  {
    "id": "SOC170",
    "title": "Passwd Found in Requested URL - Possible LFI Attack",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1006"
    ],
    "tags": [
      "LFI"
    ],
    "url": "/investigations/2026-02-12-soc170-passwd-found-in-requested-url-possible-lfi-attack/"
  },
  {
    "id": "SOC145",
    "title": "Ransomware Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1486",
      "T1490",
      "T1021-002"
    ],
    "tags": [
      "ransomware"
    ],
    "url": "/investigations/2026-02-12-soc145-ransomware-detected/"
  },
  {
    "id": "SOC141",
    "title": "Phishing URL Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-12-soc141-phishing-url-detected/"
  },
  {
    "id": "SOC138",
    "title": "Detected Suspicious Xls File",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1105"
    ],
    "tags": [
      "malware"
    ],
    "url": "/investigations/2026-02-12-soc138-detected-suspicious-xls-file/"
  },
  {
    "id": "SOC176",
    "title": "RDP Brute Force Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1110",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-02-11-soc176-rdp-brute-force-detected/"
  },
  {
    "id": "SOC127",
    "title": "SQL Injection Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059"
    ],
    "tags": [
      "sqli"
    ],
    "url": "/investigations/2026-02-11-soc127-sql-injection-detected/"
  },
  {
    "id": "SOC137",
    "title": "Malicious File or Script Download Attempt",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059",
      "T1204-002"
    ],
    "tags": [
      "malware"
    ],
    "url": "/investigations/2026-02-08-soc137-malicious-file-or-script-download-attempt/"
  }
];
