// AUTO-GENERATED by build.py — do not edit manually
// Last built: 2026-03-02 12:53:09
// Total alerts: 41

const ALERTS = [
  {
    "id": "SOC142",
    "title": "Multiple HTTP 500 Response",
    "date": "2026-03-02",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1505-003",
      "T1059",
      "T1071-001"
    ],
    "tags": [
      "revshell",
      "sqli"
    ],
    "url": "/investigations/2026-03-02-soc142-multiple-http-500-response/",
    "youtube": "https://www.youtube.com/watch?v=Yn7bDAFPtEY"
  },
  {
    "id": "SOC163",
    "title": "Suspicious Certutil.exe Usage",
    "date": "2026-03-01",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1105",
      "T1218"
    ],
    "tags": [
      "LOLBin",
      "certutil"
    ],
    "url": "/investigations/2026-03-01-soc163-suspicious-certutilexe-usage/",
    "youtube": "https://www.youtube.com/watch?v=06CnROH8rVM"
  },
  {
    "id": "SOC205",
    "title": "Malicious Macro has been executed",
    "date": "2026-02-28",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204",
      "T1059-001",
      "T1105"
    ],
    "tags": [
      "phishing",
      "powershell"
    ],
    "url": "/investigations/2026-02-28-soc205-malicious-macro-has-been-executed/",
    "youtube": "https://www.youtube.com/watch?v=4YHuizOa60k"
  },
  {
    "id": "SOC134",
    "title": "Suspicious WMI Activity",
    "date": "2026-02-28",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1047",
      "T1204",
      "T1486",
      "T1059"
    ],
    "tags": [
      "WMI"
    ],
    "url": "/investigations/2026-02-28-soc134-suspicious-wmi-activity/",
    "youtube": "https://www.youtube.com/watch?v=W3o5tSyrK_s"
  },
  {
    "id": "SOC143",
    "title": "Password Stealer Detected",
    "date": "2026-02-27",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1056"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-27-soc143-password-stealer-detected/",
    "youtube": "https://www.youtube.com/watch?v=BS44B5w17KI"
  },
  {
    "id": "SOC239",
    "title": "Remote Code Execution Detected in Splunk Enterprise",
    "date": "2026-02-26",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059",
      "T1105",
      "T1136",
      "T1505-003"
    ],
    "tags": [
      "CVE-2023-46214"
    ],
    "url": "/investigations/2026-02-26-soc239-remote-code-execution-detected-in-splunk-enterprise/",
    "youtube": "https://www.youtube.com/watch?v=yUexYuQlrVs"
  },
  {
    "id": "SOC287",
    "title": "Arbitrary File Read on Checkpoint Security Gateway [CVE-2024-24919]",
    "date": "2026-02-25",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1218-005"
    ],
    "tags": [],
    "url": "/investigations/2026-02-25-soc287-arbitrary-file-read-on-checkpoint-security-gateway-cve-2024-24919/",
    "youtube": "https://www.youtube.com/watch?v=fHAhEA-jKrY"
  },
  {
    "id": "SOC144",
    "title": "SOC144 - New scheduled task created",
    "date": "2026-02-24",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1053-005",
      "T1105",
      "T1071-001"
    ],
    "tags": [
      "persistance"
    ],
    "url": "/investigations/2026-02-24-soc144-new-scheduled-task-created/",
    "youtube": "https://www.youtube.com/watch?v=O_5Z0bZbGHc"
  },
  {
    "id": "SOC175",
    "title": "PowerShell Found in Requested URL - Possible CVE-2022-41082 Exploitation",
    "date": "2026-02-23",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059-001",
      "T1046"
    ],
    "tags": [
      "RCE"
    ],
    "url": "/investigations/2026-02-23-soc175-powershell-found-in-requested-url-possible-cve-2022-41082-exploitation/",
    "youtube": "https://www.youtube.com/watch?v=evstCoGR9nU"
  },
  {
    "id": "SOC173",
    "title": "Follina 0-Day Detected",
    "date": "2026-02-22",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204",
      "T1059-003",
      "T1203",
      "T1105",
      "T1218"
    ],
    "tags": [],
    "url": "/investigations/2026-02-22-soc173-follina-0-day-detected/",
    "youtube": "https://www.youtube.com/watch?v="
  },
  {
    "id": "SOC164",
    "title": "Suspicious Mshta Behavior",
    "date": "2026-02-21",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1218-005",
      "T1059-001",
      "T1105",
      "T1027"
    ],
    "tags": [
      "mshta"
    ],
    "url": "/investigations/2026-02-21-soc164-suspicious-mshta-behavior/",
    "youtube": "https://www.youtube.com/watch?v=DmN7Gg9VsYA"
  },
  {
    "id": "SOC282",
    "title": "SOC282 - Phishing Alert - Deceptive Mail Detected",
    "date": "2026-01-21",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1071-001",
      "T1105"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc282-phishing-alert-deceptive-mail-detected/",
    "youtube": "https://www.youtube.com/watch?v=t9YJ4-IAxdk"
  },
  {
    "id": "SOC227",
    "title": "SOC227 - Microsoft SharePoint Server Elevation of Privilege - Possible CVE-2023-29357 Exploitation",
    "date": "2026-02-20",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1068"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc227-microsoft-sharepoint-server-elevation-of-privilege-possible-cve-2023-29357-exploitation/",
    "youtube": "https://www.youtube.com/watch?v=PL8Uw6hs1Y4"
  },
  {
    "id": "SOC211",
    "title": "SOC211 - Utilman.exe Winlogon Exploit Attempt",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1546-008",
      "T1136",
      "T1068"
    ],
    "tags": [
      "LOLBin",
      "privesc"
    ],
    "url": "/investigations/2026-02-20-soc211-utilmanexe-winlogon-exploit-attempt/",
    "youtube": "https://www.youtube.com/watch?v=hpiJsYMw1aU"
  },
  {
    "id": "SOC169",
    "title": "SOC169 - Possible IDOR Attack Detected",
    "date": "2026-01-20",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1087"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc169-possible-idor-attack-detected/",
    "youtube": "https://www.youtube.com/watch?v=FNAWgTI8BOU"
  },
  {
    "id": "SOC140",
    "title": "SOC140 - Phishing Mail Detected - Suspicious Task Scheduler",
    "date": "2026-01-21",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1053"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc140-phishing-mail-detected-suspicious-task-scheduler/",
    "youtube": "https://www.youtube.com/watch?v=1lWhnfYLDDw"
  },
  {
    "id": "SOC119",
    "title": "SOC119 - Proxy - Malicious Executable File Detected",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1204"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc119-proxy-malicious-executable-file-detected/",
    "youtube": "https://www.youtube.com/watch?v=ad9d4YNMy_8"
  },
  {
    "id": "SOC114",
    "title": "SOC114 - Malicious Attachment Detected - Phishing",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1071-001"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc114-malicious-attachment-detected-phishing/",
    "youtube": "https://www.youtube.com/watch?v=4Iy8K7yG9qo"
  },
  {
    "id": "SOC109",
    "title": "SOC109 - Emotet Malware Detected",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1071-001",
      "T1105"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc109-emotet-malware-detected/",
    "youtube": "https://www.youtube.com/watch?v=rIWHgJJCtNk"
  },
  {
    "id": "SOC105",
    "title": "SOC105 - Requested T.I. URL address",
    "date": "2026-02-07",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1105"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-20-soc105-requested-ti-url-address/",
    "youtube": "https://www.youtube.com/watch?v=FjovKdW5zPQ"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected event 84",
    "date": "2026-01-23",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1204-002"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc104-malware-detected-event-84/",
    "youtube": "https://www.youtube.com/watch?v=wwaeV0Oq1dg"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected event 36",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1204-002",
      "T1105",
      "T1071-001",
      "T1486"
    ],
    "tags": [
      "ransomware"
    ],
    "url": "/investigations/2026-02-20-soc104-malware-detected-event-36/",
    "youtube": "https://www.youtube.com/watch?v=xBDJH59D9JM"
  },
  {
    "id": "SOC104",
    "title": "SOC104 - Malware Detected Event 14",
    "date": "2026-01-22",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "false-positive",
    "mitre": [
      "T1204"
    ],
    "tags": [],
    "url": "/investigations/2026-02-20-soc104-malware-detected-event-14/",
    "youtube": "https://www.youtube.com/watch?v=hDOinM80634"
  },
  {
    "id": "SOC210",
    "title": "Possible Brute Force Detected on VPN",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1105",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-02-19-soc210-possible-brute-force-detected-on-vpn/",
    "youtube": "https://www.youtube.com/watch?v=LwI0ZEuL6M4"
  },
  {
    "id": "SOC275",
    "title": "Application Token Steal Attempt Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-002",
      "T1056",
      "T1078"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-18-soc275-application-token-steal-attempt-detected/",
    "youtube": "https://www.youtube.com/watch?v=Sr_fc_LakM0"
  },
  {
    "id": "SOC250",
    "title": "APT35 HyperScrape Data Exfiltration Tool Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1567",
      "T1041",
      "T1059",
      "T1078"
    ],
    "tags": [],
    "url": "/investigations/2026-02-18-soc250-apt35-hyperscrape-data-exfiltration-tool-detected/",
    "youtube": "https://www.youtube.com/watch?v=SNroeSufrG0"
  },
  {
    "id": "SOC336",
    "title": "Windows OLE Zero-Click RCE Exploitation Detected (CVE-2025-21298)",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1203",
      "T1218-010",
      "T1105",
      "T1059-003"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-17-soc336-windows-ole-zero-click-rce-exploitation-detected-cve-2025-21298/",
    "youtube": "https://www.youtube.com/watch?v=Vcn15XrdS1k"
  },
  {
    "id": "SOC251",
    "title": "Quishing Detected (QR Code Phishing)",
    "date": "2026-02-13",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1556",
      "T1566-001",
      "T1021-002",
      "T1036"
    ],
    "tags": [
      "quishing"
    ],
    "url": "/investigations/2026-02-13-soc251-quishing-detected-qr-code-phishing/",
    "youtube": "https://www.youtube.com/watch?v=Z5SHhAj90Tg"
  },
  {
    "id": "SOC342",
    "title": "CVE\u20112025\u201153770 SharePoint ToolShell Auth Bypass and RCE",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059-001",
      "T1505-003"
    ],
    "tags": [
      "sharepoint",
      "cve-2025-53770"
    ],
    "url": "/investigations/2026-02-12-soc342-cve202553770-sharepoint-toolshell-auth-bypass-and-rce/",
    "youtube": "https://www.youtube.com/watch?v=bzQCvhPa9FM"
  },
  {
    "id": "SOC338",
    "title": "Lumma Stealer - DLL Side-Loading via Click Fix Phishing",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002",
      "T1218",
      "T1059",
      "T1105"
    ],
    "tags": [
      "spearphishing"
    ],
    "url": "/investigations/2026-02-12-soc338-lumma-stealer-dll-side-loading-via-click-fix-phishing/",
    "youtube": "https://www.youtube.com/watch?v=9uLtQAU2Y84"
  },
  {
    "id": "SOC335",
    "title": "CVE-2024-49138 Exploitation Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1078",
      "T1021-002",
      "T1059",
      "T1105"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc335-cve-2024-49138-exploitation-detected/",
    "youtube": "https://www.youtube.com/watch?v=GuRlqUA7MnQ"
  },
  {
    "id": "SOC326",
    "title": "Impersonating Domain MX Record Change Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1584",
      "T1589",
      "T1598"
    ],
    "tags": [
      "phishing",
      "spearphishing"
    ],
    "url": "/investigations/2026-02-12-soc326-impersonating-domain-mx-record-change-detected/",
    "youtube": "https://www.youtube.com/watch?v=Oinrp7zOSAg"
  },
  {
    "id": "SOC274",
    "title": "Palo Alto Networks PAN-OS Command Injection Vulnerability Exploitation (CVE-2024-3400)",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059",
      "T1505-003"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc274-palo-alto-networks-pan-os-command-injection-vulnerability-exploitation-cve-2024-3400/",
    "youtube": "https://www.youtube.com/watch?v=XsIR3zQrtwk"
  },
  {
    "id": "SOC257",
    "title": "VPN Connection Detected from Unauthorized Country",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1078",
      "T1621"
    ],
    "tags": [],
    "url": "/investigations/2026-02-12-soc257-vpn-connection-detected-from-unauthorized-country/",
    "youtube": "https://www.youtube.com/watch?v=dl7SOIIB7Yc"
  },
  {
    "id": "SOC170",
    "title": "Passwd Found in Requested URL - Possible LFI Attack",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1006"
    ],
    "tags": [
      "LFI"
    ],
    "url": "/investigations/2026-02-12-soc170-passwd-found-in-requested-url-possible-lfi-attack/",
    "youtube": "https://www.youtube.com/watch?v=uW8-8uvZ9ws"
  },
  {
    "id": "SOC145",
    "title": "Ransomware Detected",
    "date": "2026-01-26",
    "platform": "letsdefend",
    "severity": "critical",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1486",
      "T1490",
      "T1021-002"
    ],
    "tags": [
      "ransomware"
    ],
    "url": "/investigations/2026-02-12-soc145-ransomware-detected/",
    "youtube": "https://www.youtube.com/watch?v=aY5zmcRyrFw"
  },
  {
    "id": "SOC141",
    "title": "Phishing URL Detected",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1204-002"
    ],
    "tags": [
      "phishing"
    ],
    "url": "/investigations/2026-02-12-soc141-phishing-url-detected/",
    "youtube": "https://www.youtube.com/watch?v=TCJv1ndeOiU"
  },
  {
    "id": "SOC138",
    "title": "Detected Suspicious Xls File",
    "date": "2026-02-12",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1566-001",
      "T1105"
    ],
    "tags": [
      "malware"
    ],
    "url": "/investigations/2026-02-12-soc138-detected-suspicious-xls-file/",
    "youtube": "https://www.youtube.com/watch?v=_v-r9R1n1bI"
  },
  {
    "id": "SOC176",
    "title": "RDP Brute Force Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1110",
      "T1078"
    ],
    "tags": [
      "bruteforce"
    ],
    "url": "/investigations/2026-02-11-soc176-rdp-brute-force-detected/",
    "youtube": "https://www.youtube.com/watch?v=FpjV-H9zeFc"
  },
  {
    "id": "SOC127",
    "title": "SQL Injection Detected",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "high",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1190",
      "T1059"
    ],
    "tags": [
      "sqli"
    ],
    "url": "/investigations/2026-02-11-soc127-sql-injection-detected/",
    "youtube": "https://www.youtube.com/watch?v=5tyD2HPAfDA"
  },
  {
    "id": "SOC137",
    "title": "Malicious File or Script Download Attempt",
    "date": "2026-02-08",
    "platform": "letsdefend",
    "severity": "medium",
    "status": "closed",
    "outcome": "true-positive",
    "mitre": [
      "T1059",
      "T1204-002"
    ],
    "tags": [
      "malware"
    ],
    "url": "/investigations/2026-02-08-soc137-malicious-file-or-script-download-attempt/",
    "youtube": "https://www.youtube.com/watch?v=fQUIvukK9qU"
  }
];
