const LABS = [

  // ── BTL1 ──
  {
    name:     'Piggy',
    skill:    'Network Forensics',
    platform: 'BTLO',
    diff:     'Easy',
    // SSH exfil → T1048; malware infra discovery → T1590; C2 traffic in PCAP → T1071.001
    cats:     ['PCAP Analysis','Wireshark','OSINT','MITRE ATT&CK','T1048','T1590','T1071.001'],
    status:   'done',
    score:    '27/27',
    summary:  'Multi-PCAP investigation — SSH data exfiltration identification, malware infrastructure discovery, ASN attribution, MITRE ATT&CK mapping across four capture files.',
    art:      '/assets/images/labs/btl1/piggy-hero.png',
    writeup:  '/blue-team/labs/piggy/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/66',
  },
  {
    name:     'Bec-Ky',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    // BEC: account takeover → T1078; remote email collection → T1114.002; spearphishing link → T1566.002; financial fraud data manipulation → T1565.001
    cats:     ['Incident Response','BEC','Email Forensics','T1078','T1114.002','T1566.002','T1565.001'],
    status:   'done',
    score:    null,
    summary:  'Business Email Compromise investigation — suspected cyber incident involving unauthorised bank transfers from company pension fund. Trace the attacker\'s methodology.',
    art:      '/assets/images/labs/btl1/becky.png',
    writeup:  '/blue-team/labs/bec-ky/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/267',
  },
  {
    name:     'Middle Mayhem',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    // CVE-2025-29927 Next.js middleware bypass → T1190; RCE via JS → T1059.007; auth bypass → T1550; lateral via SMB → T1021.002; collection → T1005
    cats:     ['Incident Response', 'NextJS', 'Splunk', 'Initial Access', 'Defense Evasion', 'Execution', 'Credential Access', 'Lateral Movement', 'Collection',
               'T1190','T1059.007','T1550','T1021.002','T1005'],
    status:   'done',
    score:    null,
    summary:  "Your SOC team has been provided with SIEM logs from the incident. Analyze the attack pattern to determine how attackers bypassed authentication, gained remote code execution, and moved laterally through the network.",
    art:      'https://blueteamlabs.online/storage/labs/307245c21a986059462ac7363a843fb6ef1fd7e7.png',
    writeup:  '/blue-team/labs/middlemayhem/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/259',
    type:     'None',
  },
  {
    name:     'Foxy',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // Scattered Spider / UNC3944: SIM swapping account compromise → T1586; spearphishing attachment → T1566.001; valid accounts → T1078
    cats:     ['Threat Intelligence', 'Linux CLI', 'Gnumeric', 'Text Editor', 'OSINT', 'T1204.002', 'T1566',
               'T1566.001','T1586','T1078'],
    status:   'done',
    score:    null,
    summary:  'As an Intelligence Analyst you are tasked with assisting the SOC Analysts with their investigations, providing additional context',
    art:      'https://blueteamlabs.online/storage/labs/b25ff6c8e7781cbcd53b45612feb0f29c2ba9e39.png',
    writeup:  '/blue-team/labs/foxy/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/116',
  },
  {
    name:     'Anakus',
    skill:    'Malware Analysis',
    platform: 'BTLO',
    diff:     'Easy',
    // Static analysis with DIE → T1027.002 (packing); C2 via Wireshark → T1071.001; registry persistence → T1547.001; Windows cmd → T1059.003; CyberChef deobfuscation → T1140
    cats:     ['Reverse Engineering', 'CyberChef', 'Detect it Easy', 'SysinternalsSuite', 'Timeline Explorer', 'Wireshark', 'BTL1',
               'Execution', 'Persistence', 'Defense Evasion', 'Command and Control',
               'T1059.003','T1547.001','T1027.002','T1140','T1071.001'],
    status:   'done',
    score:    null,
    summary:  "It looks like the assessment will take place virtually, and I will be given a VM, with plenty of tools to analyze Threat logs and Malware",
    art:      'https://blueteamlabs.online/storage/labs/4284baac4505a217d6ae3e731f986fef446c843d.png',
    writeup:  '/blue-team/labs/anakus/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/203',
    type:     'None',
  },
  {
    name:     'Attacks',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    // Compromised Windows host event logs: LSASS dump → T1003.001; Windows cmd → T1059.003; data from local → T1005
    cats:     ['Incident Response', 'Event Viewer', 'Credential Access', 'Collection',
               'T1003.001','T1059.003','T1005'],
    status:   'done',
    score:    null,
    summary:  'Test your knowledge of MITRE ATT&CK while investigating the logs from a compromised Windows host',
    art:      'https://blueteamlabs.online/storage/labs/87ce43ac64eac1038e48ef0c5f96b953cf2eace5.png',
    writeup:  '/blue-team/labs/attacks/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/154',
    type:     'None',
  },
  {
    name:     'Spider',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // Scattered Spider: domain account discovery → T1087.002; SIM swapping → T1586; valid accounts → T1078; spearphishing link → T1566.002
    cats:     ['Threat Intelligence', 'OSINT', 'T1087', 'T1087.002', 'T1586', 'T1078', 'T1566.002'],
    status:   'done',
    score:    null,
    summary:  'Threat intelligence investigation into Scattered Spider UNC3944 — a financially motivated group leveraging social engineering, SIM swapping, and RaaS affiliations to breach high-profile organisations across multiple sectors.',
    art:      'https://blueteamlabs.online/storage/labs/485b2f8e523c798bc5cf13d4230f92dcfc6ef985.png',
    writeup:  '/blue-team/labs/spider/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/237',
    type:     'None',
  },
  {
    name:     'Splunk It',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    // Malicious link click → T1204.001; AD NTDS dump → T1003.003; Windows cmd → T1059.003; data collection → T1005
    cats:     ['Incident Response', 'Splunk BTL1', 'Credential Access', 'Collection',
               'T1204.001','T1003.003','T1059.003','T1005'],
    status:   'done',
    score:    null,
    summary:  'One of the employees clicked on a malicious link and got the endpoint compromised. After executing malicious files and getting a foothold, the attacker compromised the AD by dumping sensitive information. ',
    art:      'https://blueteamlabs.online/storage/labs/8e110194c3000089ab097ca6915c85ae966c6e5b.png',
    writeup:  '/blue-team/labs/splunkit/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/195',
    type:     'None',
  },
  {
    name:     'Gifted Crooks',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // MISP TIP lab: phishing infra domains → T1583.001; creds in files → T1552.001; data collection → T1005
    cats:     ['Threat Intel', 'OSINT', 'MISP', 'ICANN', 'Credential Access', 'Collection',
               'T1583.001','T1552.001','T1005'],
    status:   'done',
    score:    null,
    summary:  'A lab introducing players to MISP as a Threat Intelligence Platform (TIP), its practical use cases, and the fields commonly used by CTI analysts for enrichment, correlation, and reporting. ',
    art:      'https://blueteamlabs.online/storage/labs/5e14dcc05c63e06d08c2897fecc14e95e2c0394a.png',
    writeup:  '/blue-team/labs/giftedcrooks/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/269',
    type:     'None',
  },
  {
    name:     'Vortex',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    // Credential-stealing malware + SMTP data theft: spearphishing attachment → T1566.001; malicious file → T1204.002; browser creds → T1555.003; C2 → T1071.001; SMTP exfil → T1048
    cats:     ['Incident Response', 'Wireshark', 'T1566', 'T1204',
               'T1566.001','T1204.002','T1555.003','T1071.001','T1048'],
    status:   'done',
    score:    null,
    summary:  "PCAP analysis of a credential-stealing malware infection — tracing C2 traffic, decoding exfiltrated credentials, and identifying SMTP data theft from Brianas compromised workstation.",
    art:      'https://blueteamlabs.online/storage/labs/d730336d25ffa104c54785046a6e5acc43388439.png',
    writeup:  '/blue-team/labs/vortex/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/227',
    type:     'None',
  },
  {
    name:     'Exxtensity',
    skill:    'Endpoint Forensics',
    platform: 'BTLO',
    diff:     'Easy',
    // Browser extension keylogger + registry policy manipulation: registry modification → T1112; network sniffing → T1040
    cats:     ['Endpoint Forensics', 'Wireshark', 'ExtAnalysis', 'Persistence', 'Collection', 'T1176', 'T1056.001',
               'T1112','T1040'],
    status:   'done',
    score:    null,
    summary:  'Browser extension forensics identifying malicious extensions via manifest analysis, registry policy manipulation, keylogger traffic capture, and ExtAnalysis domain enumeration.',
    art:      'https://blueteamlabs.online/storage/labs/86dc3b3289829ac12c2f302bb0e01f163d36764b.png',
    writeup:  '/blue-team/labs/exxtensity/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/81',
    type:     'None',
  },

  // ── CyberDefenders ──
  {
    name:     'WebStrike',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // PHP webshell double-ext bypass → T1190 + T1505.003; netcat reverse shell → T1059.004; /etc/passwd exfil → T1552.001 + T1041
    cats:     ['Network Forensics','PCAP Analysis','Wireshark','Web Shell',
               'T1190','T1505.003','T1059.004','T1552.001','T1041'],
    status:   'done',
    score:    null,
    summary:  'Suspicious file identified on a company web server. PCAP analysis revealed a double-extension bypass (image.jpg.php) used to upload a PHP webshell, reverse shell attempt via netcat on port 8080, and /etc/passwd exfiltration attempt. Attacker attributed to Tianjin, China via IP2Location.',
    art:      'https://cyberdefenders.org/media/terraform/WebStrike/WebStrike.webp',
    writeup:  '/blue-team/labs/webstrike/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/webstrike/',
  },
  {
    name:     'Oski',
    skill:    'Malware Analysis',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Stealc stealer: browser creds → T1555.003; RC4 encrypted C2 → T1573.001; C2 over HTTP → T1071.001; packing evasion → T1027.002; cookie theft → T1539
    cats:     ['Threat Intelligence','Malware Analysis','Sandbox Analysis','Credential Access','PCAP Analysis',
               'T1555.003','T1573.001','T1071.001','T1027.002','T1539'],
    status:   'done',
    score:    null,
    summary:  'Analyzed a Stealc malware sample using VirusTotal and Any.Run to extract configuration details, identify command and control infrastructure, recover RC4 encryption keys, and map observed behaviour to MITRE ATT&CK techniques.',
    art:      'https://cyberdefenders.org/media/terraform/Oski/Oski.webp',
    writeup:  '/blue-team/labs/oski/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/oski/',
  },
  {
    name:     'PoisonedCredentials',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // LLMNR poisoning → T1557; forced authentication → T1187; pass the hash → T1550.002; SMB access → T1021.002; network sniffing → T1040
    cats:     ['Network Forensics','PCAP Analysis','Wireshark',
               'T1557','T1187','T1550.002','T1021.002','T1040'],
    status:   'done',
    score:    null,
    summary:  'Analyzed PCAP data to detect LLMNR poisoning, identify the rogue responder, extract NTLM credentials, and confirm unauthorized SMB access to the targeted host.',
    art:      'https://cyberdefenders.org/media/terraform/PoisonedCredentials/PoisonedCredentials.webp',
    writeup:  '/blue-team/labs/poisonedcredentials/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/poisonedcredentials/',
  },
  {
    name:     'Yellow Rat',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Yellow Cockatoo RAT: .lnk shortcut persistence → T1547.009; C2 → T1071.001; DLL side-loading → T1574.002; exfil over C2 → T1041; obfuscation → T1027
    cats:     ['Threat Intel', 'VirusTotal', 'Red Canary', 'Execution', 'Persistence', 'Defense Evasion', 'Command and Control', 'Exfiltration',
               'T1547.009','T1071.001','T1574.002','T1041','T1027'],
    status:   'done',
    score:    null,
    summary:  'Analyzed Yellow Cockatoo RAT DLL using VirusTotal and ANY.RUN, identifying C2 infrastructure, persistence via .lnk startup files, and solarmarker.dat drop.',
    art:      'https://cyberdefenders.org/media/terraform/Yellow%20RAT/Yellow_RAT.webp',
    writeup:  '/blue-team/labs/yellowrat/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/yellow-rat/',
  },
  {
    name:     'Amadey - APT-C-36',
    skill:    'Malware Analysis',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Amadey Trojan memory: DLL injection → T1055.001; registry persistence → T1547.001; C2 over HTTP → T1071.001; exfil → T1041; priv esc → T1068; deobfuscation → T1140
    cats:     ['Endpoint Forensics', 'Memory Analysis', 'Volatility 3',
               'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Command and Control', 'Exfiltration',
               'T1055.001','T1547.001','T1071.001','T1041','T1068','T1140'],
    status:   'done',
    score:    null,
    summary:  'Reconstruct Amadey Trojan behavior by analyzing memory dumps with Volatility3 to identify malicious processes, C2 communications, payload delivery, and persistence mechanisms.',
    art:      'https://cyberdefenders.org/media/terraform/Amadey/Amadey.webp',
    writeup:  '/blue-team/labs/amadey/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/amadey-apt-c-36/',
  },
  {
    name:     'Lespion',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // GitHub OSINT insider: search open websites → T1593; exposed creds in repo → T1552.001; crypto-mining → T1496; identity info recon → T1589
    cats:     ['Threat Intel', 'Wireshark', 'Google Maps', 'Google Image search', 'Sherlock',
               'T1593','T1552.001','T1496','T1589'],
    status:   'done',
    score:    null,
    summary:  'Investigated an insider breach using GitHub analysis and OSINT pivoting to uncover exposed credentials, crypto-mining activity, and geolocation evidence.',
    art:      'https://cyberdefenders.org/media/terraform/Lespion/Lespion.webp',
    writeup:  '/blue-team/labs/lespion/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/lespion/',
  },
  {
    name:     'The Crime',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Android ALEAPP forensics: data from local system → T1005; browser info discovery → T1217
    cats:     ['Endpoint Forensics', 'ALEAPP', 'DB Browser for SQLite',
               'T1005','T1217'],
    status:   'done',
    score:    null,
    summary:  "Utilize ALEAPP to analyze Android device artifacts, reconstructing a victim's financial details, movements, and communication patterns.",
    art:      'https://cyberdefenders.org/media/terraform/The%20Crime/The_Crime.webp',
    writeup:  '/blue-team/labs/thecrime/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/the-crime/',
  },
  {
    name:     'PSEXEC Hunt',
    skill:    'Threat Hunting',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // PsExec lateral: SMB admin shares → T1021.002; service execution → T1569.002; remote system discovery → T1018; domain account creds → T1078.002; masquerading → T1036.005
    cats:     ['Network Forensics', 'Wireshark', 'Execution', 'Defense Evasion', 'Discovery', 'Lateral Movement',
               'T1021.002','T1569.002','T1018','T1078.002','T1036.005'],
    status:   'done',
    score:    null,
    summary:  "Analyze SMB traffic in a PCAP file using Wireshark to identify PsExec lateral movement, compromised systems, user credentials, and administrative shares.",
    art:      'https://cyberdefenders.org/media/terraform/PsExec%20Hunt/PsExec_Hunt.webp',
    writeup:  '/blue-team/labs/psexechunt/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/psexec-hunt/',
  },
  {
    name:     'Red Stealer',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Stealer malware: Windows cmd → T1059.003; registry persistence → T1547.001; UAC bypass → T1548.002; packing → T1027.002; sys info → T1082; data collection → T1005; ransomware-style impact → T1486
    cats:     ['Threat Intel', 'Whois', 'VirusTotal', 'MalwareBazaar', 'ThreatFox', 'ANY.RUN',
               'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Discovery', 'Collection', 'Impact',
               'T1059.003','T1547.001','T1548.002','T1027.002','T1082','T1005','T1486'],
    status:   'done',
    score:    null,
    summary:  "Analyze a suspicious executable using VirusTotal and MalwareBazaar to extract IOCs, identify C2 infrastructure, MITRE ATT&CK techniques, and privilege escalation mechanisms.",
    art:      'https://cyberdefenders.org/media/terraform/Red%20Stealer/Red_Stealer.webp',
    writeup:  '/blue-team/labs/redstealer/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/red-stealer/',
  },
  {
    name:     '3cx Supply Chain',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // 3CX: supply chain compromise → T1195; DLL side-loading → T1574.002; security software discovery → T1518.001; sys info → T1082; masquerading → T1036.005
    cats:     ['Threat Intel', 'VirusTotal', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Discovery',
               'T1195','T1574.002','T1518.001','T1082','T1036.005'],
    status:   'done',
    score:    null,
    summary:  "Reconstruct the 3CX supply chain attack by analyzing compromised MSI and DLL artifacts to identify TTPs and attribute the incident to a threat actor.",
    art:      'https://cyberdefenders.org/media/terraform/3CX%20Supply%20Chain/3cx_supply_chain_720.webp',
    writeup:  '/blue-team/labs/3cxsupplychain/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/3cx-supply-chain/',
  },
  {
    name:     'DanaBot',
    skill:    'Malware Analysis',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // DanaBot: JS deobfuscation → T1059.007 + T1140; C2 → T1071.001; tool transfer → T1105; spearphishing link → T1566.002
    cats:     ['Network Forensics', 'Wireshark', 'VirusTotal', 'ANY.RUN', 'Network Miner', 'Execution', 'Command and Control',
               'T1059.007','T1140','T1071.001','T1105','T1566.002'],
    status:   'done',
    score:    null,
    summary:  "Analyze network traffic using Wireshark to identify DanaBot initial access, deobfuscate malicious JavaScript, and extract IOCs like IPs, file hashes, and execution processes.",
    art:      'https://cyberdefenders.org/media/terraform/DanaBot/DanaBot.webp',
    writeup:  '/blue-team/labs/danabot/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/danabot/',
  },
  {
    name:     'Volatility Traces',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Memory forensics: process hollowing → T1055.012; registry persistence → T1547.001; Windows cmd → T1059.003; obfuscation → T1027
    cats:     ['Endpoint Forensics', 'Volatility 3', 'Execution', 'Persistence',
               'T1055.012','T1547.001','T1059.003','T1027'],
    status:   'done',
    score:    null,
    summary:  "Analyze a memory dump using Volatility to identify malicious processes, persistence mechanisms, defense evasion techniques, and map them to MITRE ATT&CK.",
    art:      'https://cyberdefenders.org/media/terraform/Volatility%20Traces/Volatility_Traces_A7cz9FH.webp',
    writeup:  '/blue-team/labs/volatilitytraces/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/volatility-traces/',
  },
  {
    name:     'Insider',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Linux disk image + bash history: Unix shell → T1059.004; creds in files → T1552.001; file discovery → T1083; data from local → T1005
    cats:     ['Endpoint Forensics', 'FTK Imager', 'Execution', 'Credential Access',
               'T1059.004','T1552.001','T1083','T1005'],
    status:   'done',
    score:    null,
    summary:  "Analyze Linux disk image artifacts, including logs and Bash history, using FTK Imager to investigate insider threat activities and reconstruct user actions.",
    art:      'https://cyberdefenders.org/media/terraform/Insider/Insider_MIaRqal.webp',
    writeup:  '/blue-team/labs/insider/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/insider/',
  },
  {
    name:     'NerisBot',
    skill:    'Threat Hunting',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Suricata/Zeek C2 correlation: C2 HTTP → T1071.001; DNS C2 → T1071.004; DGA → T1568.002
    cats:     ['Threat Hunting', 'Splunk', 'Command and Control',
               'T1071.001','T1071.004','T1568.002'],
    status:   'done',
    score:    null,
    summary:  'Reconstruct the attack timeline by correlating Suricata and Zeek logs in Splunk to identify malicious IPs, C2 domains, targeted hosts, and file hashes.',
    art:      'https://cyberdefenders.org/media/terraform/NerisBot/NerisBot_uISG1hp.webp',
    writeup:  '/blue-team/labs/nerisbot/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/nerisbot/',
  },
  {
    name:     'Ramnit',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Ramnit memory forensics: process hollowing → T1055.012; masquerade legit process → T1036.005; C2 → T1071.001; decode/deobfuscate → T1140
    cats:     ['Endpoint Forensics', 'Volatility 3', 'VirusTotal', 'Execution', 'Defense Evasion', 'Command and Control',
               'T1055.012','T1036.005','T1071.001','T1140'],
    status:   'done',
    score:    null,
    summary:  "Analyze a memory dump using Volatility to identify a malicious process, extract network IOCs, file hash, and compilation timestamp, correlating with external threat intelligence.",
    art:      'https://cyberdefenders.org/media/terraform/Ramnit/Ramnit.webp',
    writeup:  '/blue-team/labs/ramnit/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/ramnit/',
  },
  {
    name:     'GrabThePhisher',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Crypto phishing kit + Telegram exfil: phishing via service → T1566.003; Telegram exfil → T1567; GUI input capture (phishing form) → T1056.002; drive-by → T1189
    cats:     ['Threat Intel', 'Text Editor', 'Initial Access', 'Exfiltration',
               'T1566.003','T1567','T1056.002','T1189'],
    status:   'done',
    score:    null,
    summary:  'Analyze a cryptocurrency phishing kit to identify exfiltration methods, extract critical IOCs, and gather threat actor intelligence using local logs and Telegram APIs.',
    art:      'https://cyberdefenders.org/media/terraform/GrabThePhisher/GrabThePhisher.webp',
    writeup:  '/blue-team/labs/grabthephisher/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/grabthephisher/',
  },
  {
    name:     'PacketDetective',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Auth + remote exec in PCAP: valid accounts → T1078; Windows cmd → T1059.003; C2 → T1071.001; SMB exec → T1021.002
    cats:     ['Network Forensics', 'Wireshark', 'Execution', 'Defense Evasion', 'Command and Control',
               'T1078','T1059.003','T1071.001','T1021.002'],
    status:   'done',
    score:    null,
    summary:  "Analyze network traffic in PCAP files using Wireshark to extract IOCs and reconstruct attacker tactics like authentication and remote execution.",
    art:      'https://cyberdefenders.org/media/terraform/PacketDetective/Packet_Detective.webp',
    writeup:  '/blue-team/labs/packetdetective/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/packetdetective/',
  },
  {
    name:     'jetbrains',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // JetBrains web server exploit + webshell + persistence: exploit public-facing → T1190; webshell → T1505.003; Unix shell → T1059.004; C2 → T1071.001
    cats:     ['Network Forensics', 'Wireshark', 'NetworkMiner', 'Brim', 'Initial Access', 'Execution', 'Command and Control',
               'T1190','T1505.003','T1059.004','T1071.001'],
    status:   'done',
    score:    null,
    summary:  'Analyze network traffic using Wireshark to identify web server exploitation, extract attacker IOCs and persistence mechanisms, and map attack techniques to MITRE ATT&CK.',
    art:      'https://cyberdefenders.org/media/terraform/JetBrains/JetBrains_w96gGwO.webp',
    writeup:  '/blue-team/labs/jetbrains/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/jetbrains/',
  },
  {
    name:     'RetailBreach',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // XSS + session token theft + lateral: exploit public-facing → T1190; XSS JS → T1059.007; session cookie theft → T1539; vuln scanning → T1595.002; SMB lateral → T1021.002; file discovery → T1083
    cats:     ['Network Forensics', 'Wireshark', 'Reconnaissance', 'Initial Access', 'Execution', 'Defense Evasion', 'Credential Access', 'Discovery', 'Lateral Movement',
               'T1190','T1059.007','T1539','T1595.002','T1021.002','T1083'],
    status:   'done',
    score:    null,
    summary:  "Investigate network traffic with Wireshark to identify attacker TTPs, extract XSS payloads and session tokens, and determine exploited web application vulnerabilities.",
    art:      'https://cyberdefenders.org/media/terraform/RetailBreach/RetailBreach_S9g8WLI.webp',
    writeup:  '/blue-team/labs/retailbreach/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/retailbreach/',
  },
  {
    name:     'Openfire',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // CVE-2023-32315: exploit public-facing → T1190; plugin upload webshell → T1505.003; cmd exec → T1059.004; network service discovery → T1046; C2 → T1071.001
    cats:     ['Network Forensics', 'Wireshark', 'Initial Access', 'Execution', 'Persistence', 'Discovery', 'Command and Control',
               'T1190','T1505.003','T1059.004','T1046','T1071.001'],
    status:   'done',
    score:    null,
    summary:  "Reconstruct an Openfire server attack timeline by analyzing PCAP files with Wireshark to identify login attempts, plugin uploads, command execution, and the exploited CVE-2023-32315 vulnerability.",
    art:      'https://cyberdefenders.org/media/terraform/Openfire/Openfire_rYHqdgk.webp',
    writeup:  '/blue-team/labs/openfire/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/openfire/',
  },
  {
    name:     'XLMRat',
    skill:    'Malware Analysis',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // XLM macro RAT: PowerShell → T1059.001; deobfuscation → T1140; command obfuscation → T1027.010; reflective/PE injection → T1055.002; spearphishing attachment → T1566.001
    cats:     ['Network Forensics', 'CyberChef', 'Wireshark', 'VirusTotal', 'Python3', 'PowerShell', 'Execution', 'Defense Evasion',
               'T1059.001','T1140','T1027.010','T1055.002','T1566.001'],
    status:   'done',
    score:    null,
    summary:  'Analyze network traffic to identify malware delivery, deobfuscate scripts, and map attacker techniques using MITRE ATT&CK, focusing on stealthy execution and reflective code loading.',
    art:      'https://cyberdefenders.org/media/terraform/XLMRat/terraform/XLMRat/xlmrat.webp',
    writeup:  '/blue-team/labs/xlmrat/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/xlmrat/',
  },
  {
    name:     'Lockdown',
    skill:    ['Malware Analysis', 'Network Forensics', 'Endpoint Forensics'],
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Multi-stage: exploit public-facing → T1190; PowerShell → T1059.001; registry persistence → T1547.001; process hollowing → T1055.012; priv esc → T1068; sys info → T1082; SMB lateral → T1021.002; C2 → T1071.001
    cats:     ['Network Forensics', 'CyberChef', 'Wireshark', 'VirusTotal', 'Volatility',
               'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Discovery', 'Lateral Movement', 'Command and Control',
               'T1190','T1059.001','T1547.001','T1055.012','T1068','T1082','T1021.002','T1071.001'],
    status:   'done',
    score:    null,
    summary:  "Reconstruct a multi-stage intrusion by analyzing network traffic, memory, and malware artifacts using Wireshark, Volatility, and VirusTotal, mapping findings to MITRE ATT&CK.",
    art:      'https://cyberdefenders.org/media/terraform/Lockdown/terraform/Lockdown/lockdown.webp',
    writeup:  '/blue-team/labs/lockdown/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/lockdown/',
  },
  {
    name:     'Maranhao',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Trojanized game installer: malicious file → T1204.002; registry persistence → T1547.001; browser creds → T1555.003; masquerade legit app → T1036.005; priv esc → T1068; data collection → T1005
    cats:     ['Endpoint Forensics', 'FTK Imager', 'Initial Access', 'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access', 'Collection',
               'T1204.002','T1547.001','T1555.003','T1036.005','T1068','T1005'],
    status:   'done',
    score:    null,
    summary:  "Investigate a trojanized game installer by analyzing browser history, logs, registry hives, and filesystem artifacts to map the full attack chain and extract IOCs.",
    art:      'https://cyberdefenders.org/media/terraform/Maranh%C3%A3o/terraform/Maranh%C3%A3o/maranhao.webp',
    writeup:  '/blue-team/labs/maranhao/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/maranhao/',
  },
  {
    name:     'ContainerBreak - Rootkit Trail',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Container escape + rootkit + hidden processes: escape to host → T1611; rootkit → T1014; Unix shell → T1059.004; hidden files → T1564.001; priv esc → T1068; C2 → T1071.001
    cats:     ['Endpoint Forensics', 'Linux Command Line Tools', 'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Command and Control',
               'T1611','T1014','T1059.004','T1564.001','T1068','T1071.001'],
    status:   'done',
    score:    null,
    summary:  "Investigated a post-container-escape Linux compromise involving rootkit installation, hidden processes, and persistence mechanisms identified through live forensic collection.",
    art:      'https://cyberdefenders.org/media/terraform/DuskUnfold0x2/terraform/DuskUnfold0x2/duskunfold0x2_ic6Ej2s.webp',
    writeup:  '/blue-team/labs/containerbreak/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/containerbreak-rootkit-trail/',
  },
  {
    name:     'SigmaPredator',
    skill:    'Detection Engineering',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Event log clearing detection: clear event logs → T1070.001; PowerShell → T1059.001; Windows cmd → T1059.003; WMI → T1047
    cats:     ['Detection Engineering', 'VsCode', 'Sigma', 'Chainsaw', 'Defense Evasion',
               'T1070.001','T1059.001','T1059.003','T1047'],
    status:   'done',
    score:    null,
    summary:  "Design and validate Sigma rules to detect event log clearing techniques across CLI, WMI, and PowerShell execution artifacts.",
    art:      'https://cyberdefenders.org/media/terraform/SigmaPredator/SigmaPredator.webp',
    writeup:  '/blue-team/labs/sigmapredator/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/sigmapredator/',
  },
  {
    name:     'AWSRaid',
    skill:    'Cloud Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // AWS CloudTrail: additional cloud creds → T1098.001; create account persistence → T1136; data from cloud storage → T1530; creds in files → T1552.001
    cats:     ['Cloud Forensics', 'Splunk', 'Persistence', 'Privilege Escalation', 'Credential Access',
               'T1098.001','T1136','T1530','T1552.001'],
    status:   'done',
    score:    null,
    summary:  "Investigate AWS CloudTrail logs using Splunk to identify unauthorized access, analyze configuration changes, and detect persistence mechanisms.",
    art:      'https://cyberdefenders.org/media/terraform/AWSRaid/AWSRaid.webp',
    writeup:  '/blue-team/labs/awsraid/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/awsraid/',
  },
  {
    name:     'XWorm',
    skill:    'Malware Analysis',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // XWorm static+dynamic: Windows cmd → T1059.003; registry persistence → T1547.001; packing → T1027.002; DLL injection → T1055.001; sys info → T1082; browser creds → T1555.003; data collection → T1005
    cats:     ['Malware Analysis', 'PEStudio', 'dnSpy', 'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access', 'Discovery', 'Collection',
               'T1059.003','T1547.001','T1027.002','T1055.001','T1082','T1555.003','T1005'],
    status:   'done',
    score:    null,
    summary:  "Analyze malware behavior to identify persistence methods, evasion techniques, and C2 infrastructure by extracting artifacts and configuration data from static and dynamic analysis.",
    art:      'https://cyberdefenders.org/media/terraform/XWorm/XWorm.webp',
    writeup:  '/blue-team/labs/xworm/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/xworm/',
  },
  {
    name:     'RaaS Unfold RansomHub',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Medium',
    // RansomHub ransomware: data encrypted → T1486; inhibit system recovery → T1490; service stop → T1489
    cats:     ['Threat Intel', 'VirusTotal', 'Google Search', 'Impact',
               'T1486','T1490','T1489'],
    status:   'done',
    score:    null,
    summary:  "A ransomware empire built on the ashes of its predecessors — trace its origins, expose its operators, and unfold its playbook.",
    art:      'https://cyberdefenders.org/media/terraform/RaaS%20Unfold%20-%20RansomHub/RaaS_Unfold_-_RansomHub.webp',
    writeup:  '/blue-team/labs/raasunfold/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/raas-unfold-ransomhub/',
  },
  {
    name:     'RediShell Kinsing',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Jenkins exploit → T1190; container escape to host → T1611; Unix shell → T1059.004; priv esc → T1068; creds in files → T1552.001
    cats:     ['Network Forensics', 'Wireshark', 'Initial Access', 'Execution', 'Privilege Escalation', 'Credential Access',
               'T1190','T1611','T1059.004','T1068','T1552.001'],
    status:   'done',
    score:    null,
    summary:  "The packet capture was killed mid-attack. Race against incomplete evidence to reconstruct how attackers breached Jenkins, pivoted through containers, and escaped to the host",
    art:      'https://cyberdefenders.org/media/terraform/RediShell%20-%20Kinsing/RediShell_-_Kinsing.webp',
    writeup:  '/blue-team/labs/redishell/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/redishell-kinsing/',
  },
  {
    name:     'Tomcat Takeover',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // Tomcat compromise: exploit public-facing → T1190; webshell → T1505.003; Unix shell → T1059.004; vuln scanning → T1595.002; file discovery → T1083; local account creds → T1078.003
    cats:     ['Network Forensics', 'Wireshark', 'Reconnaissance', 'Execution', 'Persistence', 'Privilege Escalation', 'Credential Access', 'Discovery', 'Command and Control',
               'T1190','T1505.003','T1059.004','T1595.002','T1083','T1078.003'],
    status:   'done',
    score:    null,
    summary:  "Analyze network traffic using Wireshark's custom columns, filters, and statistics to identify suspicious web server administration access and potential compromise.",
    art:      'https://cyberdefenders.org/media/terraform/Tomcat%20Takeover/Tomcat_Takeover.webp',
    writeup:  '/blue-team/labs/tomcat-takeover/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/tomcat-takeover/',
  },
  {
    name:     'XXE Infiltration',
    skill:    'Network Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // XXE: exploit public-facing → T1190; webshell persistence → T1505.003; creds in files → T1552.001; vuln scanning → T1595.002; data collection → T1005; exfil → T1041
    cats:     ['Network Forensics', 'Wireshark Brim', 'Reconnaissance', 'Initial Access', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access', 'Discovery', 'Collection', 'Exfiltration',
               'T1190','T1505.003','T1552.001','T1595.002','T1005','T1041'],
    status:   'done',
    score:    null,
    summary:  'Analyze PCAP data using Wireshark to identify XXE vulnerabilities, extract compromised credentials, and detect web shell uploads for persistence.',
    art:      'https://cyberdefenders.org/media/terraform/XXE%20Infiltration/XXE_Infiltration_dOfBhTu.webp',
    writeup:  '/blue-team/labs/xxeinfiltration/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/xxe-infiltration/',
    type:     'None',
  },
  {
    name:     'MBuchus',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Medium',
    // Malvertising campaign: drive-by compromise → T1189; attacker infra domains → T1583.001; upload malware → T1608.001; C2 → T1071.001
    cats:     ['Threat Intel', 'OSINT', 'VirusTotal', 'crt.sh', 'Resource Development', 'Command and Control',
               'T1189','T1583.001','T1608.001','T1071.001'],
    status:   'done',
    score:    null,
    summary:  'Utilize OSINT, VirusTotal, and crt.sh to analyze a multi-stage malvertising campaign, identifying initial access, malware payloads, and attacker infrastructure.',
    art:      'https://cyberdefenders.org/media/terraform/MBuchus/terraform/MBuchus/mbuchus.webp',
    writeup:  '/blue-team/labs/mbuchus/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/mbuchus/',
    type:     'None',
  },
  {
    name:     'REvil - GOLD SOUTHFIELD',
    skill:    'Threat Hunting',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // REvil ransomware: data encrypted → T1486; inhibit recovery (vssadmin/bcdedit cmds) → T1490; Windows cmd to decode sabotage → T1059.003; Tor C2 tunneling → T1572; LSASS dump → T1003.001; data collection → T1005
    cats:     ['Threat Hunting', 'Splunk', 'OSINT', 'Credential Access', 'Collection',
               'T1486','T1490','T1059.003','T1572','T1003.001','T1005'],
    status:   'done',
    score:    null,
    summary:  'Analyze Sysmon logs in Elastic SIEM to investigate REvil ransomware attack behaviors, decode recovery sabotage commands, and identify IOCs including the C2 onion domain.',
    art:      'https://cyberdefenders.org/media/terraform/REvil/REvil.webp',
    writeup:  '/blue-team/labs/revil_gold/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/revil-gold-southfield/',
    type:     'None',
  },

  // ── LetsDefend ──
  {
    name:     'SOC Analyst Path',
    skill:    'Threat Hunting',
    platform: 'LetsDefend',
    diff:     'Medium',
    // 34 SIEM investigations: phishing → T1566.001 + T1566.002; malware beaconing → T1071.001; brute force → T1110.003; lateral → T1021.002; exfil → T1041
    cats:     ['Alert Triage','SIEM','Malware','Phishing','Network',
               'T1566.001','T1566.002','T1071.001','T1110.003','T1021.002','T1041'],
    status:   'done',
    score:    '97%',
    summary:  '34 real-world SIEM alert investigations — phishing, malware beaconing, brute force, lateral movement, data exfiltration. Structured triage methodology documented across all cases.',
    art:      '/assets/images/labs/letsdefend/letsdefend.png',
    writeup:  'https://app.letsdefend.io/user/inkedqt',
    proof:    null,
  },

  // ── TryHackMe ──
  {
    name:     'Advent of Cyber 2025 (SOC-mas)',
    skill:    'Incident Response',
    platform: 'TryHackMe',
    diff:     'Easy',
    // Broad blue team: phishing → T1566.001; Splunk/PowerShell detections → T1059.001; host forensics → T1005; network traffic → T1071.001; malicious file → T1204.002
    cats:     ['SOC','Splunk','DFIR','Phishing','Network Forensics',
               'T1566.001','T1059.001','T1005','T1071.001','T1204.002'],
    status:   'done',
    score:    null,
    summary:  '24 daily blue team challenges — phishing analysis, Splunk detections, alert triage, host forensics, network traffic analysis, and malware basics. Certified completion.',
    art:      'https://raw.githubusercontent.com/inkedqt/ctf-writeups/main/HTB/proofs/thm_advent2025.png',
    writeup:  'https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-2H6JFCWHKX.pdf',
    proof:    null,
  },
  {
    name:     'Night Shift CTF',
    skill:    'Incident Response',
    platform: 'TryHackMe',
    diff:     'Medium',
    // SOC simulation: PowerShell → T1059.001; phishing → T1566.001; valid accounts → T1078; SMB lateral → T1021.002
    cats:     ['SOC Simulation','Alert Triage','Log Correlation','IR',
               'T1059.001','T1566.001','T1078','T1021.002'],
    status:   'done',
    score:    null,
    summary:  'Week-long SOC analyst simulation — 9 realistic enterprise scenarios covering alert triage, severity assessment, multi-source log correlation, and incident response.',
    art:      'https://raw.githubusercontent.com/inkedqt/ctf-writeups/main/HTB/proofs/THM_first_shift.png',
    writeup:  'https://tryhackme.com/inkedqt',
    proof:    null,
  },

  // ── HackSmarter ──
  {
    name:     'Source Leak Investigation',
    skill:    'Incident Response',
    platform: 'HackSmarter',
    diff:     'Easy',
    // Source code breach: data from local → T1005; exfil over C2 → T1041; valid accounts used → T1078
    cats:     ['Incident Response','DFIR','Digital Forensics',
               'T1005','T1041','T1078'],
    status:   'done',
    score:    null,
    summary:  'First IR investigation: source code breach at indie game studio. Evidence collection, timeline analysis, root cause identification, and report writing.',
    art:      'https://raw.githubusercontent.com/inkedqt/ctf-writeups/main/assets/images/labs/hacksmarter-source-leak.png',
    writeup:  'https://www.hacksmarter.org/courses/b0ecedbe-d142-48bf-9b6d-f58ccdbd4b44',
    proof:    null,
  },

  // ── BTLO Challenges ──
  {
    name:     'Follina',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // CVE-2022-30190 MSDT: exploitation for client execution → T1203; spearphishing attachment → T1566.001; malicious file → T1204.002; Windows cmd → T1059.003
    cats:     ['Threat Intelligence', 'VirusTotal', 'Any.Run', 'OSINT',
               'T1203','T1566.001','T1204.002','T1059.003'],
    status:   'done',
    score:    null,
    summary:  'On a Friday evening when you were in a mood to celebrate your weekend, your team was alerted with a new RCE vulnerability actively being exploited.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/9956bc4835437bb7deb40e2e498e7956f1fc5209.png',
    writeup:  '/blue-team/labs/follina/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/43',
    type:     'challenge',
  },
  {
    name:     'Squid Game',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Medium',
    // Steganography: obfuscated files → T1027; creds in files → T1552.001; data collection → T1005
    cats:     ['Threat Intelligence', 'Google', 'Steghide', 'Stegsolve.jar', 'Python', 'Credential Access', 'Collection',
               'T1027','T1552.001','T1005'],
    status:   'done',
    score:    null,
    summary:  'Will you survive the Squid Games?',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/6c1aab7ad9ef3f74d5b632d02bc43ad5c35e46ba.png',
    writeup:  '/blue-team/labs/squidgame/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/33',
    type:     'challenge',
  },
  {
    name:     'The Report',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // 2022 threat report study: OS credential dumping → T1003; data collection → T1005; phishing → T1566
    cats:     ['Threat Intel', 'OSINT', 'Credential Access', 'Collection',
               'T1003','T1005','T1566'],
    status:   'done',
    score:    null,
    summary:  'As part of gathering intel you were assigned a task to study a threat report released in 2022 and suggest some useful outcomes for your SOC.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/b1ec49c9408d8e1af21b21083b9de81fcad55c29.png',
    writeup:  '/blue-team/labs/thereport/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/42',
    type:     'challenge',
  },
  {
    name:     'ATT&CK',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // ATT&CK scenario-based: Windows cmd → T1059.003; C2 HTTP → T1071.001
    cats:     ['Threat Intelligence', 'Mitre attack framework', 'Execution', 'Command and Control',
               'T1059.003','T1071.001'],
    status:   'done',
    score:    null,
    summary:  'See how you can operationalize the MITRE ATT&CK framework to solve these scenario-based problems. ',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/a5af13bcbfd3f4487f33493646eabc4a07d617c6.png',
    writeup:  '/blue-team/labs/attack_btlo/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/15',
    type:     'challenge',
  },
  {
    name:     'D3FEND',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    // D3FEND framework — no specific ATT&CK T-codes applicable
    cats:     ['Threat Intelligence', 'D3FEND Framework'],
    status:   'done',
    score:    null,
    summary:  'Navigating the MITRE D3FEND framework to identify defensive techniques, tactics, artifacts and open-source tooling mapped to ATT&CK.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/4483c9698a1377a56b1ab536b91bf825de5a227f.png',
    writeup:  '/blue-team/labs/d3fend/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/27',
    type:     'challenge',
  },
  {
    name:     'Shiba Insider',
    skill:    'Network Forensics',
    platform: 'BTLO',
    diff:     'Easy',
    // Insider network forensics: network sniffing → T1040; exfil over alt protocol → T1048
    cats:     ['Network Forensics', 'Wireshark', 'T1040','T1048'],
    status:   'done',
    score:    null,
    summary:  'Can you uncover the insider?',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/11a8f79de6e4fb84c35ea56f84dd5da869b54931.png',
    writeup:  '/blue-team/labs/shibainsider/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/29',
    type:     'challenge',
  },
  {
    name:     'Meta',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    // EXIF metadata OSINT: gather victim identity info → T1589; gather victim host info → T1592
    cats:     ['Threat Intelligence', 'exiftool', 'reverse image search', 'T1589','T1592'],
    status:   'done',
    score:    null,
    summary:  'OSINT and metadata forensics challenge — extracting EXIF data from suspect images to locate a criminal on the run.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/979c2ccfa0ff3cac981c6445a575c77ba804b8bf.png',
    writeup:  '/blue-team/labs/meta/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/39',
    type:     'challenge',
  },

  {
    name:     'Redline',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    cats:     ['Endpoint Forensics', 'Volatility', 'strings', 'Privilege Escalation', 'Defense Evasion', 'Command and Control', 'Exfiltration', 'T1055', 'T1036.005', 'T1071.001', 'T1041', 'T1555.003', 'T1572', 'T1105'],
    status:   'done',
    score:    null,
    summary:  'Analyze a Windows memory dump using Volatility 3 to identify Redline stealer malware, trace attacker C2 infrastructure, and determine how the attacker bypassed the Network Intrusion Detection System via VPN tunneling.',
    art:      'https://cyberdefenders.org/media/terraform/RedLine/RedLine.webp',
    writeup:  '/blue-team/labs/redline/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/redline/',
    type:     'None',
  },

  {
    name:     'IcedID',
    skill:    'Threat Intelligence',
    platform: 'CyberDefenders',
    diff:     'Easy',
    cats:     ['Threat Intel', 'VirusTotal', 'Any.run', 'tria.ge', 'WHOIS', 'Initial Access', 'Execution', 'Persistence', 'Defense Evasion', 'Command and Control', 'Exfiltration', 'T1566.001', 'T1204.002', 'T1105', 'T1027.002', 'T1071.001', 'T1573.002', 'T1048.002', 'T1547.001', 'T1185', 'T1189'],
    status:   'done',
    score:    null,
    summary:  'Pure threat intelligence investigation into an IcedID malware sample — analyzing a malicious Excel macro dropper via hash lookup across VirusTotal, Any.run, and tria.ge to map C2 infrastructure, identify the threat actor GOLD CABIN, and document the staged payload delivery chain.',
    art:      'https://cyberdefenders.org/media/terraform/IcedID/IcedID_4yYxbLQ.webp',
    writeup:  '/blue-team/labs/icedid/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/icedid/',
    type:     'None',
  },

  {
    name:     'Revenge Hotels APT',
    skill:    'Endpoint Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    cats:     ['Endpoint Forensics', 'CyberChef', 'DB Browser for SQLite', 'dnSpy', 'Windows Event Viewer', 'Initial Access', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access', 'Discovery', 'Lateral Movement', 'Collection', 'Exfiltration', 'T1566.001', 'T1204.002', 'T1059.005', 'T1059.001', 'T1027', 'T1562.001', 'T1547.001', 'T1543', 'T1071.001', 'T1005', 'T1560.001', 'T1041'],
    status:   'done',
    score:    null,
    summary:  'Reconstruct a multi-stage RevengeHotels APT intrusion by correlating Chrome browser history, Sysmon event logs, registry artifacts, and .NET malware analysis to trace the full attack chain from phishing JS dropper through Quasar RAT persistence and data exfiltration.',
    art:      'https://cyberdefenders.org/media/terraform/RevengeHotels%20APT/terraform/RevengeHotels%20APT/revengehotels-apt.webp',
    writeup:  '/blue-team/labs/revengehotels/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/revengehotels-apt/',
    type:     'None',
  },

  {
    name:     'Winter Stew',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Incident Response', 'Wireshark', 'Reconnaissance', 'Initial Access', 'Credential Access', 'T1595', 'T1595.001', 'T1190', 'T1552.001', 'T1133'],
    status:   'done',
    score:    null,
    summary:  'Analyze a network capture from a chemical plant DMZ monitoring workstation to identify reconnaissance activity, discover a dual-homed host, confirm nmap and ARP scanning, and extract SCADA system credentials transmitted in cleartext over HTTP.',
    art:      'https://blueteamlabs.online/storage/labs/a2c1c52ad2308713635395cd4972ecc557664d20.png',
    writeup:  '/blue-team/labs/winterstew/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/181',
    type:     'None',
  },

  {
    name:     'Rogue Azure',
    skill:    'Cloud Forensics',
    platform: 'CyberDefenders',
    diff:     'Easy',
    cats:     ['Cloud Forensics', 'Microsoft Sentinel', 'Azure Monitor', 'KQL Query Editor', 'Azure AD Sign-in Logs', 'Initial Access', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access', 'Discovery', 'Lateral Movement', 'Collection', 'Exfiltration', 'T1110.003', 'T1078', 'T1550.001', 'T1136', 'T1098.001', 'T1484.001', 'T1530', 'T1567'],
    status:   'done',
    score:    null,
    summary:  'Investigate a multi-stage Azure tenant compromise by querying sign-in logs, audit logs, and storage blob logs using KQL in Microsoft Sentinel to identify a password spray attack, post-exploitation persistence via malicious app registrations, privilege escalation to Global Administrator, and sensitive file exfiltration from Azure Blob Storage.',
    art:      'https://cyberdefenders.org/media/terraform/Rogue%20Azure/terraform/Rogue%20Azure/rogue-azure.webp',
    writeup:  '/blue-team/labs/rogueazure/',
    proof:    'https://cyberdefenders.org/blueteam-ctf-challenges/achievements/inksec/rogue-azure/',
    type:     'None',
  },

  {
    name:     'Deep Blue',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Incident Response', 'DeepBlue', 'CLI PowerShell', 'Event Viewer', 'T1133', 'T1078.003', 'T1136.001', 'T1543.003', 'T1059.003', 'T1021.001'],
    status:   'done',
    score:    null,
    summary:  'A Windows workstation was recently compromised, and evidence suggests it was an attack against internet-facing RDP, then Meterpreter was deployed to conduct \'Actions on Objectives\'. Can you verify these findings? ',
    art:      'https://blueteamlabs.online/storage/labs/25e54a30fb8f836f469ffcf348d0d5759d26e4bd.png',
    writeup:  '/blue-team/labs/deepblue/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/32',
    type:     'None',
  },

  {
    name:     'Print',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Incident Response', 'Wireshark', 'Event Viewer', 'Lateral Movement', 'Execution', 'Command and Control', 'T1210', 'T1059'],
    status:   'done',
    score:    null,
    summary:  'PrintNightmare exploit analysis — tracing DLL injection via SMB, Windows Print Spooler abuse, reverse shell callback identification, and WerFault parent process forensics.',
    art:      'https://blueteamlabs.online/storage/labs/f51510dc7f994f01337b731adaa1c8b06e959ce9.png',
    writeup:  '/blue-team/labs/print/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/73',
    type:     'None',
  },

  {
    name:     'Blocker',
    skill:    'Detection Engineering',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Detection Engineering', 'Sysmon', 'Event Viewer', 'URLHaus', 'Defense Evasion', 'Execution'],
    status:   'done',
    score:    null,
    summary:  'Sysmon 14 FileBlockExecutable analysis — identifying blocked executable events, threat hunting via hash enrichment, and writing preventative Sysmon configuration rules. ',
    art:      'https://blueteamlabs.online/storage/labs/a7284ee974e016ef8d49fe2504ea9892a1cc5e51.png',
    writeup:  '/blue-team/labs/blocker/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/112',
    type:     'None',
  },

  {
    name:     'Indicators',
    skill:    'Endpoint Forensics',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Endpoint Forensics', 'PowerShell', 'Text Editor', 'Exiftool', 'MalwareBazaar', 'VirusTotal', 'Command and Control', 'Execution', 'T1105'],
    status:   'done',
    score:    null,
    summary:  'Static malware analysis of a Mirai botnet sample — extracting indicators via Exiftool, Zone Identifiers, hash enrichment, and manual binary inspection',
    art:      'https://blueteamlabs.online/storage/labs/f3b3ab4922f9bff6c2981583edb5bd2188eac799.png',
    writeup:  '/blue-team/labs/indicators/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/104',
    type:     'None',
  },

  {
    name:     'Spilled Bucket',
    skill:    'Cloud Forensics',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Cloud Forensics', 'Splunk', 'T1651', 'T1580', 'T1098.003'],
    status:   'done',
    score:    null,
    summary:  'The attackers were successful in attacking and gaining access to their cloud infrastructure. Can you help them out?',
    art:      'https://blueteamlabs.online/storage/labs/bf54d9e7f7017a8b512a95b62a9627c91e3a3bf1.png',
    writeup:  '/blue-team/labs/spilledbucket/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/232',
    type:     'None',
  },

  {
    name:     'Multi Stages',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Incident Response', 'Wireshark Volatility', 'T1587.001 T1059 T1086'],
    status:   'done',
    score:    null,
    summary:  'A Cobalt Strike intrusion investigated across network and memory artifacts — identifying the beacon, staged PowerShell delivery, and a four-stage process injection chain using Wireshark and Volatility3.',
    art:      'https://blueteamlabs.online/storage/labs/590d1412e585c7e818030d1e08b5fc5558fe2bfd.png',
    writeup:  '/blue-team/labs/multistages/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/83',
    type:     'None',
  },

  {
    name:     'Deep Phish',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Incident Response', 'Thunderbird', 'Text Editor', 'Chrome Developer Tools', 'Wireshark', 'T1566.002'],
    status:   'done',
    score:    null,
    summary:  'Dig into a phishing email and website to uncover more secrets... ',
    art:      'https://blueteamlabs.online/storage/labs/6c2be1378e2db6055d0f032e5714dbf98e7f909a.png',
    writeup:  '/blue-team/labs/deepphish/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/140',
    type:     'None',
  },

  {
    name:     'Gothic Panda 1',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Threat Intelligence', 'MITRE ATT&CK Navigator', 'OSINT', 'Google Dorks'],
    status:   'done',
    score:    null,
    summary:  'CHANGE ME',
    art:      'https://blueteamlabs.online/storage/labs/7bd52a566c4bdadc55e8da4032e1f51fb7164a69.png',
    writeup:  '/blue-team/labs/gothicpanda1/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/234',
    type:     'None',
  },

  {
    name:     'Trend',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Incident Response', 'Wireshark', 'Persistence', '1078.001', 'T1059', 'T1105', 'T1059.003'],
    status:   'done',
    score:    null,
    summary:  'A threat actor already inside the network exploited a TRENDnet TEW-652BRU router using CVE-2019-11399, a command injection vulnerability in the router\'s web interface.',
    art:      'https://blueteamlabs.online/storage/labs/0e95d52a7b1bb4cb56b381e1a36a7143e3f8dfb5.png',
    writeup:  '/blue-team/labs/trend/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/254',
    type:     'None',
  },

  {
    name:     'bruteforce',
    skill:    'Network Forensics',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Network Forensics', 'grep', 'excel', 'T1110.001', 'T1078'],
    status:   'done',
    score:    null,
    summary:  'Analysis of Windows Security Event logs revealing an RDP brute force attack targeting the local Administrator account from a Vietnamese IP address, generating over 3000 Audit Failure events.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/801436163080cfe8f2ebc6f2de48607f6001144d.png',
    writeup:  '/blue-team/labs/bruteforce/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/40',
    type:     'challenge',
  },

  {
    name:     'Paranoid',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Incident Response', 'aureport', 'T1110.001', 'T1046', 'T1059.004', 'T1068', 'T1005', 'T1070.002'],
    status:   'done',
    score:    null,
    summary:  'Analysis of Linux auditd logs revealing an SSH brute force attack against a local account, followed by post-exploitation enumeration via LinPEAS, privilege escalation using a compiled CVE-2021-3156 (Baron Samedit) exploit, and exfiltration of /etc/shadow before the attacker cleaned up their tracks.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/8aa05047966639cf91688bbf0dafcc4c479f846a.png',
    writeup:  '/blue-team/labs/paranoid/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/30',
    type:     'challenge',
  },

  {
    name:     'Network Analysis - Ransomware',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Incident Response', 'Wireshark', 'TCPDump', 'T1486', 'T1071.001', 'T1041'],
    status:   'done',
    score:    null,
    summary:  'Analysis of ransomware network traffic to identify a TeslaCrypt infection, recover the malicious executable, and decrypt an encrypted tender document using the Cisco Talos TeslaCrypt decryptor — made possible by TeslaCrypt\'s authors publicly releasing their master key in 2016.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/04c2ea39fcc6759e500419a2f84fc585ef99c650.png',
    writeup:  '/blue-team/labs/ransomware_abc/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/30',
    type:     'challenge',
  },

  {
    name:     'ILoveYou',
    skill:    'Endpoint Forensics',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Endpoint Forensics', 'Text Editor', 'Regshot', 'T1566.001', 'T1059.005', 'T1547.001', 'T1204.002'],
    status:   'done',
    score:    null,
    summary:  'Static analysis of the infamous ILOVEYOU VBScript worm from 2000 using olevba, examining its email propagation mechanism, file infection routines, registry persistence, IRC spreading, and the embedded Barok password-stealing trojan.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/776f552527c0c868c9243ebb6cb9ad6230b94eb9.png',
    writeup:  '/blue-team/labs/CHANGE-ME/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/14',
    type:     'challenge',
  },

  {
    name:     'Teh Report II',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Incident Response', 'PDF'],
    status:   'done',
    score:    null,
    summary:  'Analysis of the MITRE \'11 Strategies of a World-Class Cybersecurity Operations Center\' to extract key SOC concepts including organisational models, workflow, tooling standards, data retention, and red teaming approaches.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/0f360991c24d7875b7e7c5f2307479b8cdb38d77.png',
    writeup:  '/blue-team/labs/thereport2/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/44',
    type:     'challenge',
  },

  {
    name:     'Fungames',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Incident Response', 'Wireshark', 'CyberChef', 'VirusTotal', 'Credential Access', 'Collection', 'TA0031', 'TA0010', 'T1190', 'T1078', 'T1059.004', 'T1068', 'T1071.004'],
    status:   'done',
    score:    null,
    summary:  'Full attack chain analysis of a PCAP from FunGames, an e-commerce platform. The attacker used SQLmap to extract credentials via SQLi, SSHed in with stolen creds, escalated to root via CVE-2024-1086 (Linux kernel netfilter exploit), then exfiltrated a customer\'s credit card data encoded as hex over a single malformed DNS query.',
    art:      'https://blueteamlabs.online/storage/labs/1cccaf0a76bf83c066f29ce71016c4786aded972.png',
    writeup:  '/blue-team/labs/fungames/',
    proof:    'https://blueteamlabs.online/achievement/share/144656/223',
    type:     'None',
  },


  {
    name:     'Phising analysis 2',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Threat Intelligence', 'Text Editor', 'Thunderbird', 'T1566.002'],
    status:   'done',
    score:    null,
    summary:  'Analysis of a phishing email impersonating Amazon, delivered to saintington73@outlook.com. The email body is base64 encoded HTML, the CTA button points to a typosquatted domain, and the attacker left a personal Facebook profile URL embedded in the footer.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/6156a19eafa9b683f8616ae21d677fac47e20834.png',
    writeup:  '/blue-team/labs/phishinganalysis2/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/24',
    type:     'challenge',
  },

  {
    name:     'Log Analysis Sysmon',
    skill:    'Endpoint Forensics',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Endpoint Forensics', 'Text Editor', 'PowerShell', 'Linux CLI', 'Command and Control', 'T1574.007', 'T1134.001'],
    status:   'done',
    score:    null,
    summary:  'You are provided with Sysmon logs from a compromised endpoint. Analyse the logs to find out the steps and techniques used by the attacker.',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/84e68852f4699766babf4f590e883bb24e403288.png',
    writeup:  '/blue-team/labs/loganalysissysmon/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/18',
    type:     'challenge',
  },

  {
    name:     'Secrets',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Incident Response', 'hashcat', 'jwt.io', 'Defense Evasion', 'Execution', 'T1110.002', 'T1078', 'T1550.001', 'T1606.001'],
    status:   'done',
    score:    null,
    summary:  'You’re a senior cyber security engineer and during your shift, we have intercepted/noticed a high privilege actions from unknown source that could be identified as malicious. ',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/6c8716189e006bfa2ca4881ccabef56b4d99c167.png',
    writeup:  '/blue-team/labs/secrets/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/35',
    type:     'challenge',
  },

  {
    name:     'Veriarty',
    skill:    'Threat Intelligence',
    platform: 'BTLO',
    diff:     'Medium',
    cats:     ['Threat Intelligence', 'hashcat', 'veracrypt', 'gpp', 'T1027', 'T1027.003', 'T1140', 'T1553', 'T1560', 'T1564.001', 'T1573'],
    status:   'done',
    score:    null,
    summary:  'DI Lestrade has intercepted a transmission from a criminal known as Moriarty',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/b17fa3b4085a6dc90f61c050a7f0326df12c3a21.png',
    writeup:  '/blue-team/labs/veriarty/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/36',
    type:     'challenge',
  },

  {
    name:     'injectionpart4',
    skill:    'Malware Analysis',
    platform: 'BTLO',
    diff:     'Easy',
    cats:     ['Malware Analysis', 'IDA', 'codebrowser', 'ghira', 'Defense Evasion', 'Execution', 'T1055.002', 'T1059.001', 'T1105', 'T1027', 'T1140'],
    status:   'done',
    score:    null,
    summary:  'Reverse engineer the given file and understand the behavior. You can use any disassembler you like to complete this challenge. ',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/5680dc738c3f92cf0f202c66875be626640e2f32.png',
    writeup:  '/blue-team/labs/injectionpart4/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/41',
    type:     'challenge',
  },

  {
    name:     'secure shell',
    skill:    'Incident Response',
    platform: 'BTLO',
    diff:     'Hard',
    cats:     ['Incident Response', 'linux-cli', 'T1110', 'T1078', 'T1021.004'],
    status:   'done',
    score:    null,
    summary:  'We had a SSH service on a system and noticed unusual change in size of the log file. ',
    art:      'https://d2ghw05x0obr70.cloudfront.net/thumbnails/f938ccab8738797243659e599219f6b978126441.png',
    writeup:  '/blue-team/labs/secureshell/',
    proof:    'https://blueteamlabs.online/achievement/share/challenge/144656/17',
    type:     'challenge',
  },

];
