// Auto-generated by get_commands.py — do not edit manually
// Run: python3 get_commands.py <labname>

const COMMANDS_DATA = [
  {
    "command": "ip.addr == 192.168.232.162 llmnr && ip.addr == 192.168.232.162",
    "tool": "wireshark",
    "lab": "PoisonedCredentials",
    "lab_url": "/blue-team/labs/poisonedcredentials/",
    "desc": "Filter Wireshark for LLMNR traffic from a specific host. Used to identify LLMNR poisoning attempts where an attacker responds to broadcast name resolution requests.",
    "tags": "wireshark llmnr poisoning broadcast name resolution"
  },
  {
    "command": "llmnr && ip.addr == 192.168.232.215",
    "tool": "wireshark",
    "lab": "PoisonedCredentials",
    "lab_url": "/blue-team/labs/poisonedcredentials/",
    "desc": "Isolate LLMNR packets from a specific IP. Useful for confirming which host is sending or responding to LLMNR queries during a poisoning investigation.",
    "tags": "wireshark llmnr poisoning responder"
  },
  {
    "command": "ntlmssp.auth.username && ip.addr == 192.168.232.215",
    "tool": "wireshark",
    "lab": "PoisonedCredentials",
    "lab_url": "/blue-team/labs/poisonedcredentials/",
    "desc": "Filter for NTLM authentication packets from a specific IP. Reveals usernames captured during NTLM relay or credential theft via LLMNR poisoning.",
    "tags": "wireshark ntlm credentials username authentication capture"
  },
  {
    "command": "./vol.py -f ../../Artifacts/Windows\\ 7\\ x64-Snapshot4.vmem windows.pstree.PsTree",
    "tool": "volatility",
    "lab": "amadey",
    "lab_url": "/blue-team/labs/amadey/",
    "desc": "Display process tree from a Windows 7 memory snapshot. Shows parent-child process relationships to identify unusual spawning chains.",
    "tags": "volatility process tree parent child hierarchy"
  },
  {
    "command": "./vol.py -f ../../Artifacts/Windows\\ 7\\ x64-Snapshot4.vmem cmdline",
    "tool": "volatility",
    "lab": "amadey",
    "lab_url": "/blue-team/labs/amadey/",
    "desc": "Extract command line arguments for all processes in the memory snapshot. Reveals execution parameters, paths, and flags used at runtime.",
    "tags": "volatility cmdline arguments execution parameters"
  },
  {
    "command": "./vol.py -f ../../Artifacts/Windows\\ 7\\ x64-Snapshot4.vmem windows.netscan.NetScan",
    "tool": "volatility",
    "lab": "amadey",
    "lab_url": "/blue-team/labs/amadey/",
    "desc": "Scan memory for active and closed network connections. Maps processes to remote IPs and ports to identify C2 communication.",
    "tags": "volatility network connections c2 ip port remote"
  },
  {
    "command": "`./vol.py -f ../../Artifacts/Windows\\ 7\\ x64-Snapshot4.vmem  windows.memmap.Memmap --pid 2748 --dump` strings pid.2748.dmp | grep -A 5 -i \"^get /\"",
    "tool": "volatility",
    "lab": "amadey",
    "lab_url": "/blue-team/labs/amadey/",
    "desc": "Dump memory for a specific PID then extract strings to find HTTP GET requests. Useful for recovering C2 URLs or download activity from a malicious process.",
    "tags": "volatility memmap dump strings http get url c2 pid"
  },
  {
    "command": "./vol.py -f ../../Artifacts/Windows\\ 7\\ x64-Snapshot4.vmem windows.filescan.FileScan > filescan.txt",
    "tool": "volatility",
    "lab": "amadey",
    "lab_url": "/blue-team/labs/amadey/",
    "desc": "Scan memory for file objects and redirect output to a text file. Saves results for grepping specific filenames and virtual addresses for later extraction.",
    "tags": "volatility filescan file objects virtual address output"
  },
  {
    "command": "http.request.method == \"GET\"",
    "tool": "wireshark",
    "lab": "danabot",
    "lab_url": "/blue-team/labs/danabot/",
    "desc": "Wireshark display filter for HTTP GET requests only. Useful for isolating download activity and C2 beacon traffic in a PCAP.",
    "tags": "wireshark http get request filter download"
  },
  {
    "command": "echo \"UGljYXNzb0JhZ3VldHRlOTk=\" | base64 -d",
    "tool": "shell",
    "lab": "lespion",
    "lab_url": "/blue-team/labs/lespion/",
    "desc": "Decode a base64 encoded string. Common technique for recovering obfuscated credentials, commands, or configuration data found in malware artifacts.",
    "tags": "shell base64 decode obfuscation credentials"
  },
  {
    "command": "index=* sourcetype=suricata eventtype=suricata_eve_ids_attack | stats values(dest_ip) values(http.http_user_agent) values(http.http_content_type) values(http.http_protocol) values(http.status) values(http.hostname) values(http.url) by src_ip",
    "tool": "splunk",
    "lab": "nerisbot",
    "lab_url": "/blue-team/labs/nerisbot/",
    "desc": "Aggregate Suricata IDS attack events by source IP. Collapses thousands of alerts into actionable rows showing user agents, hostnames, and URLs per attacker IP.",
    "tags": "splunk suricata ids aggregate stats src_ip user agent url hostname"
  },
  {
    "command": "index=* sourcetype=zeek:files tx_hosts=\"195.88.191.59\" | table _time md5 sha1 sha256",
    "tool": "splunk",
    "lab": "nerisbot",
    "lab_url": "/blue-team/labs/nerisbot/",
    "desc": "Pull all files transferred from a specific host using Zeek file logs. Returns timestamps and hashes for VirusTotal submission and IOC documentation.",
    "tags": "splunk zeek files hashes md5 sha1 sha256 tx_hosts download"
  },
  {
    "command": "index=* sourcetype=zeek:files tx_hosts=\"195.88.191.59\" | join left=L right=R where L.seen_bytes=R.bytes [search index=* sourcetype=suricata src_ip=147.32.84.165 dest_ip=195.88.191.59 url=*] | table L.md5, R.url",
    "tool": "splunk",
    "lab": "nerisbot",
    "lab_url": "/blue-team/labs/nerisbot/",
    "desc": "Correlate Zeek file hashes with Suricata HTTP URLs. Maps downloaded file hashes to the exact URLs they were retrieved from. Replace IPs as needed.",
    "tags": "splunk zeek suricata join correlate files url hash download"
  },
  {
    "command": "ntlmssp.challenge.target_name",
    "tool": "wireshark",
    "lab": "psexechunt",
    "lab_url": "/blue-team/labs/psexechunt/",
    "desc": "Filter for NTLM challenge packets containing the target domain or hostname. Helps identify the server being authenticated against during lateral movement.",
    "tags": "wireshark ntlm challenge target domain hostname lateral movement"
  },
  {
    "command": "ntlmssp.auth.username",
    "tool": "wireshark",
    "lab": "psexechunt",
    "lab_url": "/blue-team/labs/psexechunt/",
    "desc": "Filter for NTLM authentication packets to extract usernames. Identifies which accounts were used during PsExec or other remote execution activity.",
    "tags": "wireshark ntlm authentication username psexec lateral movement"
  },
  {
    "command": "smb2.tree",
    "tool": "wireshark",
    "lab": "psexechunt",
    "lab_url": "/blue-team/labs/psexechunt/",
    "desc": "Filter for SMB2 tree connect requests. Reveals which shares were accessed \u2014 ADMIN$, IPC$, or C$ connections are strong indicators of PsExec or remote service installation.",
    "tags": "wireshark smb2 tree share admin psexec remote execution"
  },
  {
    "command": "vol -f memory.dmp windows.netscan.NetScan",
    "tool": "volatility",
    "lab": "ramnit",
    "lab_url": "/blue-team/labs/ramnit/",
    "desc": "List active and closed network connections from memory. Used to identify C2 communication \u2014 maps process names and PIDs to remote IPs and ports.",
    "tags": "volatility netscan network connections c2 remote ip port"
  },
  {
    "command": "vol -f memory.dmp windows.filescan | grep \"ChromeSetup\"",
    "tool": "volatility",
    "lab": "ramnit",
    "lab_url": "/blue-team/labs/ramnit/",
    "desc": "Scan memory for file objects and filter by filename. Locates the virtual address of a specific file needed for extraction with dumpfiles.",
    "tags": "volatility filescan grep filename virtual address locate"
  },
  {
    "command": "vol -f memory.dmp windows.dumpfiles --virtaddr 0xca82b85325a0",
    "tool": "volatility",
    "lab": "ramnit",
    "lab_url": "/blue-team/labs/ramnit/",
    "desc": "Extract a specific file from memory using its virtual address obtained from filescan. Output file can then be hashed and submitted to VirusTotal.",
    "tags": "volatility dumpfiles extract virtaddr virtual address file"
  },
  {
    "command": "sha256sum file.0xca82b85325a0.0xca82b7e06c80.ImageSectionObject.ChromeSetup.exe.img sha1sum file.0xca82b85325a0.0xca82b7e06c80.ImageSectionObject.ChromeSetup.exe.img",
    "tool": "shell",
    "lab": "ramnit",
    "lab_url": "/blue-team/labs/ramnit/",
    "desc": "Hash a Volatility-extracted memory image file for VirusTotal submission. Volatility dumpfiles output uses this long naming convention \u2014 hash both SHA256 and SHA1.",
    "tags": "shell hash sha256 sha1 virustotal extracted memory image"
  },
  {
    "command": "python3 vol.py -f memory.dmp windows.psscan",
    "tool": "volatility",
    "lab": "volatilitytraces",
    "lab_url": "/blue-team/labs/volatilitytraces/",
    "desc": "Scan physical memory for process structures. Unlike pslist, catches hidden or terminated processes that have been unlinked from the standard process list.",
    "tags": "volatility psscan process scan physical memory hidden unlinked"
  },
  {
    "command": "python3 vol.py -f memory.dmp windows.cmdline",
    "tool": "volatility",
    "lab": "volatilitytraces",
    "lab_url": "/blue-team/labs/volatilitytraces/",
    "desc": "Extract full command line arguments for all processes. Reveals attacker intent \u2014 PowerShell flags, exclusion paths, and execution parameters are visible here.",
    "tags": "volatility cmdline arguments powershell parameters execution intent"
  },
  {
    "command": "python3 vol.py -f memory.dmp windows.getsids | grep -i powershell",
    "tool": "volatility",
    "lab": "volatilitytraces",
    "lab_url": "/blue-team/labs/volatilitytraces/",
    "desc": "Map processes to user accounts via SID, filtered for PowerShell. Links malicious process activity to a specific local or domain user account.",
    "tags": "volatility getsids sid user account privilege powershell attribution"
  },
  {
    "command": "http.request.method == \"POST\"",
    "tool": "wireshark",
    "lab": "webstrike",
    "lab_url": "/blue-team/labs/webstrike/",
    "desc": "Filter for HTTP POST requests in Wireshark. Useful for identifying form submissions, file uploads, exploit payloads, or data exfiltration over HTTP.",
    "tags": "wireshark http post request filter upload exfiltration"
  },
  {
    "command": "ip.addr == 117.11.88.124",
    "tool": "wireshark",
    "lab": "webstrike",
    "lab_url": "/blue-team/labs/webstrike/",
    "desc": "Filter all Wireshark traffic to or from a specific IP address. Used to isolate attacker traffic once a suspicious IP has been identified.",
    "tags": "wireshark ip filter isolate attacker traffic"
  },
  {
    "command": "`tcp.port == 8080`",
    "tool": "wireshark",
    "lab": "webstrike",
    "lab_url": "/blue-team/labs/webstrike/",
    "desc": "Filter traffic on a specific TCP port. Port 8080 is commonly used for alternative HTTP, web shells, or C2 callbacks to avoid standard port detection.",
    "tags": "wireshark tcp port 8080 http webshell c2 filter"
  },
  {
    "command": "smb2 && ip.addr == 172.16.66.1",
    "tool": "wireshark",
    "lab": "packetdetective",
    "lab_url": "/blue-team/labs/packetdetective/",
    "desc": "Filter SMB2 traffic to identify files written by attacker IP, revealing remote execution via PSEXESVC.exe",
    "tags": "wireshark"
  },
  {
    "command": "http && ip.addr == 23.158.56.196 && http.request.method == \"POST\"",
    "tool": "wireshark",
    "lab": "jetbrains",
    "lab_url": "/blue-team/labs/jetbrains/",
    "desc": "Filter HTTP POST requests from attacker IP to identify webshell uploads and command execution activity",
    "tags": "wireshark"
  },
  {
    "command": "http && ip.addr == 111.224.180.128 and frame contains \"lqkctf24s9h9lg67teu8uevn3q\"",
    "tool": "wireshark",
    "lab": "retailbreach",
    "lab_url": "/blue-team/labs/retailbreach/",
    "desc": "Filter attacker traffic containing the stolen session cookie to confirm hijacked session usage",
    "tags": "wireshark"
  },
  {
    "command": "ip.addr==10.0.2.4 && smb2",
    "tool": "wireshark",
    "lab": "lockdown",
    "lab_url": "/blue-team/labs/lockdown/",
    "desc": "Filter SMB2 traffic from attacker IP to identify share enumeration and file upload activity",
    "tags": "wireshark"
  },
  {
    "command": "vol -f memdump.mem windows.info",
    "tool": "volatility",
    "lab": "lockdown",
    "lab_url": "/blue-team/labs/lockdown/",
    "desc": "Dump system information from memory image including kernel base address and OS version",
    "tags": "volatility"
  },
  {
    "command": "vol -f memdump.mem windows.pstree",
    "tool": "volatility",
    "lab": "lockdown",
    "lab_url": "/blue-team/labs/lockdown/",
    "desc": "Display running process tree from memory to identify suspicious parent-child relationships and injected processes",
    "tags": "volatility"
  },
  {
    "command": "vol -f memdump.mem windows.cmdline",
    "tool": "volatility",
    "lab": "lockdown",
    "lab_url": "/blue-team/labs/lockdown/",
    "desc": "Extract full command line arguments for all running processes to identify malicious execution paths and persistence mechanisms",
    "tags": "volatility"
  },
  {
    "command": "index=* \"userIdentity.userName\"=\"helpdesk.luke\" eventName=GetObject | stats min(_time) as first_access_timestamp",
    "tool": "splunk",
    "lab": "awsraid",
    "lab_url": "/blue-team/labs/awsraid/",
    "desc": "Find the earliest S3 GetObject event for a specific IAM user \u2014 returns first access timestamp as epoch",
    "tags": "splunk"
  },
  {
    "command": "index=\"aws_cloudtrail\" \"userIdentity.userName\"=\"helpdesk.luke\" eventSource=\"s3.amazonaws.com\" eventName=\"GetObject\" | table _time, eventName, requestParameters.bucketName, requestParameters.key",
    "tool": "splunk",
    "lab": "awsraid",
    "lab_url": "/blue-team/labs/awsraid/",
    "desc": "List all S3 objects accessed by a specific IAM user \u2014 shows bucket name and object key per event",
    "tags": "splunk"
  },
  {
    "command": "index=\"aws_cloudtrail\" \"userIdentity.userName\"=\"helpdesk.luke\" eventName=PutBucketPublicAccessBlock | stats count by requestParameters.bucketName",
    "tool": "splunk",
    "lab": "awsraid",
    "lab_url": "/blue-team/labs/awsraid/",
    "desc": "Detect S3 bucket public access block modifications by a specific user \u2014 attacker staging data for public exfiltration",
    "tags": "splunk"
  },
  {
    "command": "`index=\"aws_cloudtrail\" \"userIdentity.userName\"=\"helpdesk.luke\" eventCategory=\"Management\" | search eventName=\"CreateUser\" OR eventName=\"CreateLoginProfile\"| table _time, eventName, requestParameters.userName`",
    "tool": "splunk",
    "lab": "awsraid",
    "lab_url": "/blue-team/labs/awsraid/",
    "desc": "Hunt for IAM backdoor account creation \u2014 finds CreateUser and CreateLoginProfile events used to establish persistence",
    "tags": "splunk"
  },
  {
    "command": "index=\"aws_cloudtrail\" \"userIdentity.userName\"=\"helpdesk.luke\" eventName=AddUserToGroup | stats count by requestParameters.groupName",
    "tool": "splunk",
    "lab": "awsraid",
    "lab_url": "/blue-team/labs/awsraid/",
    "desc": "Identify group membership changes made by a compromised IAM user \u2014 detects privilege escalation via admin group assignment",
    "tags": "splunk"
  },
  {
    "command": "ip.addr == 185.220.101.50 and tcp.port == 4444",
    "tool": "wireshark",
    "lab": "redishell",
    "lab_url": "/blue-team/labs/redishell/",
    "desc": "Filter Wireshark to isolate reverse shell traffic between victim and C2 on port 4444 for TCP stream reconstruction",
    "tags": "wireshark"
  },
  {
    "command": "kill -9 24918",
    "tool": "shell",
    "lab": "redishell",
    "lab_url": "/blue-team/labs/redishell/",
    "desc": "kill -9 24918 Attacker terminates active tcpdump process to stop network capture and destroy forensic evidence",
    "tags": "shell"
  },
  {
    "command": "cat * | grep -c \"https://cdn.discordapp.com/\"",
    "tool": "shell",
    "lab": "foxy",
    "lab_url": "/blue-team/labs/foxy/",
    "desc": "Count occurrences of a string across all files in a directory. -c returns a line count per file rather than the matching lines themselves.",
    "tags": "shell"
  },
  {
    "command": "index=* src_ip=\"218.92.0.204\" | stats count by http_request_uri | sort -count",
    "tool": "splunk",
    "lab": "middlemayhem",
    "lab_url": "/blue-team/labs/middlemayhem/",
    "desc": "Count and rank unique URIs accessed by attacker IP to measure scan scope",
    "tags": "splunk"
  },
  {
    "command": "index=* src_ip=\"<webserver_ip>\" dest_port=22 | stats count by dest_ip | sort -count",
    "tool": "splunk",
    "lab": "middlemayhem",
    "lab_url": "/blue-team/labs/middlemayhem/",
    "desc": "Identify internal hosts targeted by SSH brute-force from compromised web server",
    "tags": "splunk"
  },
  {
    "command": "index=* User=\"CYBERRANGE\\\\ricksanchez\" \"schtasks.exe\"",
    "tool": "splunk",
    "lab": "splunkit",
    "lab_url": "/blue-team/labs/splunkit/",
    "desc": "Hunt scheduled task creation by a specific user. Useful for detecting persistence via schtasks.exe under a compromised account.",
    "tags": "splunk"
  },
  {
    "command": "index=* User=\"CYBERRANGE\\\\ricksanchez\" \".ps1\"",
    "tool": "splunk",
    "lab": "splunkit",
    "lab_url": "/blue-team/labs/splunkit/",
    "desc": "Hunt PowerShell script execution by a specific user. Useful for detecting malicious .ps1 activity under a compromised account.",
    "tags": "splunk"
  },
  {
    "command": "tcp.flags.syn == 1 && tcp.flags.ack == 1",
    "tool": "wireshark",
    "lab": "xxeinfiltration",
    "lab_url": "/blue-team/labs/xxeinfiltration/",
    "desc": "Filter for completed TCP handshakes (SYN-ACK). Used to identify open ports on a target during attacker reconnaissance.",
    "tags": "wireshark"
  },
  {
    "command": "mysql.login_request",
    "tool": "wireshark",
    "lab": "xxeinfiltration",
    "lab_url": "/blue-team/labs/xxeinfiltration/",
    "desc": "Filter for MySQL login attempts in a PCAP. Used to identify credential-based database access following credential theft.",
    "tags": "wireshark"
  },
  {
    "command": "index=revil \"event.code\"=11 \"readme\"",
    "tool": "splunk",
    "lab": "revil_gold",
    "lab_url": "/blue-team/labs/revil_gold/",
    "desc": "Hunt for ransom note file creation via Sysmon Event ID 11. Filtering on 'readme' identifies ransomware-dropped notes and surfaces the responsible process ID and executable path.",
    "tags": "splunk"
  },
  {
    "command": "index=revil powershell.exe \"event.code\"=1",
    "tool": "splunk",
    "lab": "revil_gold",
    "lab_url": "/blue-team/labs/revil_gold/",
    "desc": "Hunt for PowerShell process execution via Sysmon Event ID 1. Used to identify obfuscated commands such as Base64-encoded shadow copy deletion during ransomware investigations.",
    "tags": "splunk"
  },
  {
    "command": "index=revil event.code=1 \"facebook assistant.exe\" | table winlog.event_data.Hashes",
    "tool": "splunk",
    "lab": "revil_gold",
    "lab_url": "/blue-team/labs/revil_gold/",
    "desc": "Extract all hashes logged by Sysmon for a specific executable at process creation. Returns SHA256, MD5, SHA1 and IMPHASH for immediate threat intel cross-referencing.",
    "tags": "splunk"
  },
  {
    "command": "exiftool image.jpg",
    "tool": "shell",
    "lab": "shibainsider",
    "lab_url": "/blue-team/labs/shibainsider/",
    "desc": "Extract metadata from image file to identify embedded technique hints",
    "tags": "shell"
  },
  {
    "command": "steghide extract -sf image.jpg",
    "tool": "shell",
    "lab": "shibainsider",
    "lab_url": "/blue-team/labs/shibainsider/",
    "desc": "Extract hidden data from steganographic image using steghide",
    "tags": "shell"
  },
  {
    "command": "exiftool uploaded_1.JPG | grep -i \"date\" exiftool uploaded_1.JPG | grep -i \"comment\"",
    "tool": "shell",
    "lab": "meta",
    "lab_url": "/blue-team/labs/meta/",
    "desc": "Extract metadata from image file to identify embedded technique hints",
    "tags": "shell"
  },
  {
    "command": "tcp.port == 14693",
    "tool": "wireshark",
    "lab": "exxtensity",
    "lab_url": "/blue-team/labs/exxtensity/",
    "desc": "Filter traffic on non-standard port 14693 keylogger exfil port in Exxtensity",
    "tags": "wireshark"
  },
  {
    "command": "vol -f MemoryDump.mem windows.pstree",
    "tool": "volatility",
    "lab": "redline",
    "lab_url": "/blue-team/labs/redline/",
    "desc": "Display running processes as parent/child tree to identify anomalous spawning relationships",
    "tags": "volatility"
  },
  {
    "command": "vol -f MemoryDump.mem windows.pslist",
    "tool": "volatility",
    "lab": "redline",
    "lab_url": "/blue-team/labs/redline/",
    "desc": "List all running processes from memory with PID, PPID, start time",
    "tags": "volatility"
  },
  {
    "command": "vol -f MemoryDump.mem windows.malfind",
    "tool": "volatility",
    "lab": "redline",
    "lab_url": "/blue-team/labs/redline/",
    "desc": "Scan memory regions for injected code \u2014 flags PAGE_EXECUTE_READWRITE and suspicious VAD entries",
    "tags": "volatility"
  },
  {
    "command": "vol -f MemoryDump.mem windows.netscan",
    "tool": "volatility",
    "lab": "redline",
    "lab_url": "/blue-team/labs/redline/",
    "desc": "Enumerate active and recently closed network connections from memory",
    "tags": "volatility"
  },
  {
    "command": "strings -el MemoryDump.mem | grep \"\\.php\" | sort -u",
    "tool": "shell",
    "lab": "redline",
    "lab_url": "/blue-team/labs/redline/",
    "desc": "Extract UTF-16 wide strings from memory dump and filter for PHP endpoints \u2014 catches .NET malware C2 URLs",
    "tags": "shell"
  },
  {
    "command": "vol -f MemoryDump.mem windows.filescan | grep -i oneetx.exe",
    "tool": "volatility",
    "lab": "redline",
    "lab_url": "/blue-team/labs/redline/",
    "desc": "can memory for file handles and filter by name to recover full on-disk path of a malicious executable",
    "tags": "volatility"
  },
  {
    "command": "EvtxECmd.exe -f \"C:\\Users\\Administrator\\Desktop\\Start Here\\Artifacts\\PC\\Windows\\System32\\winevt\\Logs\\Microsoft-Windows-Sysmon%4Operational.evtx\" --csv \"C:\\Temp\" --csvf sysmon.csv",
    "tool": "shell",
    "lab": "revengehotels",
    "lab_url": "/blue-team/labs/revengehotels/",
    "desc": "Export Windows event log to CSV for proper Timeline Explorer analysis \u2014 raw evtx renders unreadable without Sysmon installed on analysis host",
    "tags": "shell"
  },
  {
    "command": "ip.addr == 192.168.90.5 && http.request.method == POST",
    "tool": "wireshark",
    "lab": "winterstew",
    "lab_url": "/blue-team/labs/winterstew/",
    "desc": "Filter HTTP POST requests from a specific host \u2014 used to extract login credentials submitted via web forms",
    "tags": "wireshark"
  },
  {
    "command": "http.response.code == 302",
    "tool": "wireshark",
    "lab": "winterstew",
    "lab_url": "/blue-team/labs/winterstew/",
    "desc": "Filter HTTP 302 redirect responses \u2014 identifies successful logins and post-authentication redirects",
    "tags": "wireshark"
  },
  {
    "command": "search * | distinct $table | order by $table asc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: discover all available tables in the Sentinel workspace \u2014 run first on any new lab to confirm table names before writing queries",
    "tags": "kql"
  },
  {
    "command": "InteractiveSignIns_CL | where Status == \"Failure\" | summarize FailedAttempts = count(), TargetUsers = dcount(Username) by IPAddress | order by FailedAttempts desc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: detect password spray \u2014 count failures and distinct target users per IP, high TargetUsers from single IP = spray pattern",
    "tags": "kql"
  },
  {
    "command": "InteractiveSignIns_CL | where IPAddress == \"52.59.240.166\" | where Status == \"Success\" | project EventTime, Username, IPAddress, Status | order by EventTime asc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: confirm successful logins from a known spray IP to identify the first compromised account",
    "tags": "kql"
  },
  {
    "command": "InteractiveSignIns_CL | where Username == \"mharmon@compliantsecure.store\" | where Status == \"Success\" | project EventTime, Username, IPAddress, Status, Location | order by EventTime asc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: track all successful logins for a compromised account \u2014 reveals IP pivot and geolocation changes post-compromise",
    "tags": "kql"
  },
  {
    "command": "AuditLogs_CL | where EventTime >= datetime(2025-11-14) | where ActorUserPrincipalName == \"mharmon@compliantsecure.store\" | project EventTime, Activity, ActorUserPrincipalName, Target1DisplayName, IPAddress | order by EventTime asc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: full post-exploitation audit trail for a compromised account \u2014 surfaces app registrations, role assignments, and all admin actions after breach",
    "tags": "kql"
  },
  {
    "command": "AuditLogs_CL | where Activity == \"Add member to role\" | where EventTime >= datetime(2025-11-14) | project EventTime, ActorUserPrincipalName, Target1DisplayName, TargetUserPrincipalName, NewRule, IPAddress | order by EventTime asc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: identify privilege escalation \u2014 shows role assignments made by the attacker including Global Administrator grants",
    "tags": "kql"
  },
  {
    "command": "StorageBlobLogs_CL | where TimeGenerated >= datetime(2025-11-14) | where OperationName == \"GetBlob\" | project TimeGenerated, AccountName, Uri, CallerIpAddress, OperationName | order by TimeGenerated asc",
    "tool": "kql",
    "lab": "rogueazure",
    "lab_url": "/blue-team/labs/rogueazure/",
    "desc": "KQL: detect data exfiltration from Azure Blob Storage \u2014 GetBlob operations show files downloaded and the caller IP",
    "tags": "kql"
  },
  {
    "command": "ip.addr == 10.0.2.5 && smb2",
    "tool": "wireshark",
    "lab": "print",
    "lab_url": "/blue-team/labs/print/",
    "desc": "Filter SMB2 traffic from attacker IP to identify malicious file transfers",
    "tags": "wireshark"
  },
  {
    "command": "Get-Content .\\sh4 -Stream Zone.Identifier",
    "tool": "powershell",
    "lab": "indicators",
    "lab_url": "/blue-team/labs/indicators/",
    "desc": "Read NTFS Zone Identifier stream to determine file download origin URL",
    "tags": "powershell"
  },
  {
    "command": "Get-FileHash .\\sh4",
    "tool": "powershell",
    "lab": "indicators",
    "lab_url": "/blue-team/labs/indicators/",
    "desc": "Calculate SHA256 hash of file for threat intelligence enrichment",
    "tags": "powershell"
  },
  {
    "command": "index=* eventSource=\"s3.amazonaws.com\" eventName=\"GetObject\" | table eventTime, sourceIPAddress, requestParameters.bucketName, requestParameters.key, userAgent",
    "tool": "splunk",
    "lab": "spilledbucket",
    "lab_url": "/blue-team/labs/spilledbucket/",
    "desc": "CloudTrail: query S3 GetObject events to identify attacker IP, bucket name, and downloaded file",
    "tags": "splunk"
  },
  {
    "command": "index=* dstport=51820 | table start, srcaddr, dstaddr, dstport, protocol | sort start",
    "tool": "splunk",
    "lab": "spilledbucket",
    "lab_url": "/blue-team/labs/spilledbucket/",
    "desc": "VPC Flow Logs: find WireGuard connections on UDP 51820 to identify attacker IP and target EC2",
    "tags": "splunk"
  },
  {
    "command": "index=* eventName=\"AssumeRole\" sourceIPAddress!=\"resource-explorer-2.amazonaws.com\" | table eventTime, sourceIPAddress, requestParameters.roleArn | sort eventTime",
    "tool": "splunk",
    "lab": "spilledbucket",
    "lab_url": "/blue-team/labs/spilledbucket/",
    "desc": "CloudTrail: find AssumeRole events excluding AWS service noise to identify attacker role assumption",
    "tags": "splunk"
  },
  {
    "command": "index=* eventSource=\"iam.amazonaws.com\" \"i-00eda415438b3d90c\" | table eventTime, eventName, requestParameters | sort eventTime",
    "tool": "splunk",
    "lab": "spilledbucket",
    "lab_url": "/blue-team/labs/spilledbucket/",
    "desc": "CloudTrail: query IAM events tied to compromised instance ID to surface enumeration and persistence actions",
    "tags": "splunk"
  },
  {
    "command": "index=* dstport=22 | table start, srcaddr, dstaddr, dstport | sort start",
    "tool": "splunk",
    "lab": "spilledbucket",
    "lab_url": "/blue-team/labs/spilledbucket/",
    "desc": "VPC Flow Logs: identify SSH lateral movement by filtering inbound connections on port 22",
    "tags": "splunk"
  },
  {
    "command": "index=* srcaddr=\"10.0.2.32\" protocol=6 | stats count by dstaddr, dstport | sort -count",
    "tool": "splunk",
    "lab": "spilledbucket",
    "lab_url": "/blue-team/labs/spilledbucket/",
    "desc": "VPC Flow Logs: find outbound TCP connections from compromised EC2 to identify reverse shell C2 IP and port",
    "tags": "splunk"
  },
  {
    "command": "ip.src == 192.168.100.97 && http",
    "tool": "wireshark",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Wireshark: filter HTTP traffic from attacker IP to identify Cobalt Strike beacon URIs and encoded cookie data",
    "tags": "wireshark"
  },
  {
    "command": "ip.src == 192.168.100.100 && http.request.method == \"GET\"",
    "tool": "wireshark",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Wireshark: filter outbound GET requests from victim to identify C2 staging URL and payload delivery",
    "tags": "wireshark"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.cmdline",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: dump full process command lines to identify malicious PowerShell download cradle",
    "tags": "volatility"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.cmdline | grep \"powershell\\|rundll32\\|explorer\"",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: filter cmdline output for key processes to map the attack execution chain",
    "tags": "volatility"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.pstree",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: display process tree to identify parent-child injection chain across four stages",
    "tags": "volatility"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.netscan",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: scan network artifacts in memory to confirm beacon process PID actively connecting to C2 on port 80",
    "tags": "volatility"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.malfind | grep -i \"PAGE_EXECUTE_READWRITE\"",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: detect injected memory regions with RWX permissions indicating shellcode injection into legitimate processes",
    "tags": "volatility"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.hivelist",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: list registry hives in memory to locate SYSTEM hive offset for key extraction",
    "tags": "volatility"
  },
  {
    "command": "python3 vol.py -f ../../Investigation\\ Files/memdump.raw windows.registry.printkey --offset 0xf8a0007b010 --key \"Microsoft\\Cryptography\"",
    "tool": "volatility",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Volatility: extract MachineGuid from registry hive to identify unique Windows endpoint identifier",
    "tags": "volatility"
  },
  {
    "command": "$s=New-Object IO.MemoryStream([Convert]::FromBase64String(\"...\"))",
    "tool": "powershell",
    "lab": "multistages",
    "lab_url": "/blue-team/labs/multistages/",
    "desc": "Cobalt Strike stager response \u2014 reflective DLL loader delivered as base64-encoded blob via PowerShell MemoryStream",
    "tags": "powershell"
  },
  {
    "command": "aureport -if audit.log --summary",
    "tool": "shell",
    "lab": "paranoid",
    "lab_url": "/blue-team/labs/paranoid/",
    "desc": "Generate a summary report from a specified audit log file",
    "tags": "shell"
  },
  {
    "command": "aureport -if audit.log --login --failed",
    "tool": "shell",
    "lab": "paranoid",
    "lab_url": "/blue-team/labs/paranoid/",
    "desc": "List failed login attempts from a specified audit log file",
    "tags": "shell"
  },
  {
    "command": "aureport -if audit.log --login --success",
    "tool": "shell",
    "lab": "paranoid",
    "lab_url": "/blue-team/labs/paranoid/",
    "desc": "List successful logins from a specified audit log file",
    "tags": "shell"
  }
];

const COMMANDS_META = {
  "total": 92,
  "labs": 32,
  "tools": [
    "kql",
    "powershell",
    "shell",
    "splunk",
    "volatility",
    "wireshark"
  ]
};
