// Auto-generated by get_commands.py — do not edit manually
// Run: python3 get_commands.py <labname>

const COMMANDS_DATA = [
  {
    "command": "cat * | grep -c \"https://cdn.discordapp.com/\"",
    "tool": "shell",
    "lab": "foxy",
    "lab_url": "/blue-team/labs/foxy/",
    "desc": "",
    "tags": "shell"
  }
];

const COMMANDS_META = {
  "total": 1,
  "labs": 1,
  "tools": [
    "shell"
  ]
};
