#!/usr/bin/env python3
"""
extract_commands.py
Scans all LABS/*/index.md files, extracts ```bash code blocks,
auto-detects tool, and outputs commands-data.js for commands.html
"""

import os
import re
import json
import sys

# ── CONFIG ──────────────────────────────────────────────────────────────────
LABS_DIR = os.path.expanduser(
    "~/Documents/Obsidian_vault/Hack Academy's Blue Team Obsidian Notes/Cyber_Defenders/LABS"
)
OUTPUT_JS = os.path.expanduser("~/portfolio-v2/blue-team/commands/commands-data.js")

# ── TOOL DETECTION ───────────────────────────────────────────────────────────
TOOL_PATTERNS = [
    ("volatility", [r"\bvol\.py\b", r"\bvol\s+-f\b", r"windows\.\w+", r"volatility"]),
    ("splunk",     [r"\bindex=", r"\bsourcetype=", r"\bstats\s+", r"\btable\s+_time", r"\bdedup\b", r"\bwhere\b.*=.*\b(?:ip|host)\b"]),
    ("zeek",       [r"sourcetype=zeek", r"\bzeek:", r"tx_hosts=", r"id\.orig_h"]),
    ("wireshark",  [r"http\.request", r"tcp\.stream", r"ip\.src\s*==", r"ip\.dst\s*==", r"dns\.qry", r"frame\.number"]),
    ("nmap",       [r"\bnmap\b"]),
    ("tshark",     [r"\btshark\b"]),
    ("grep",       [r"^\s*grep\b"]),
]

def detect_tool(command: str) -> str:
    """Auto-detect tool from command content."""
    cmd = command.lower()
    for tool, patterns in TOOL_PATTERNS:
        for pattern in patterns:
            if re.search(pattern, cmd):
                return tool
    return "shell"

# ── EXTRACT ──────────────────────────────────────────────────────────────────
def extract_commands_from_md(filepath: str, lab_name: str) -> list:
    """Extract all ```bash blocks from a markdown file."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Match ```bash ... ``` blocks
    pattern = re.compile(r"```bash\s*\n(.*?)```", re.DOTALL)
    blocks = pattern.findall(content)

    commands = []
    for block in blocks:
        # Handle multi-line commands — split on newlines, skip comment lines and blanks
        lines = block.strip().split("\n")

        # Check for explicit tool override: # tool: wireshark
        tool_override = None
        clean_lines = []
        for line in lines:
            tool_match = re.match(r"#\s*tool:\s*(\w+)", line.strip())
            if tool_match:
                tool_override = tool_match.group(1).lower()
            elif line.strip() and not line.strip().startswith("#"):
                clean_lines.append(line)

        if not clean_lines:
            continue

        # Join multi-line commands (lines ending with \ or | at end)
        full_command = " ".join(l.strip() for l in clean_lines)

        tool = tool_override or detect_tool(full_command)

        commands.append({
            "command": full_command,
            "tool": tool,
            "lab": lab_name,
            "lab_url": f"/blue-team/labs/{lab_name.lower().replace(' ', '')}/",
            "desc": "",   # placeholder — fill in manually or extend script
            "tags": tool,
        })

    return commands

# ── MAIN ─────────────────────────────────────────────────────────────────────
def main():
    if not os.path.isdir(LABS_DIR):
        print(f"ERROR: LABS_DIR not found: {LABS_DIR}")
        sys.exit(1)

    all_commands = []
    lab_count = 0
    tool_set = set()

    for lab_folder in sorted(os.listdir(LABS_DIR)):
        lab_path = os.path.join(LABS_DIR, lab_folder)
        if not os.path.isdir(lab_path):
            continue

        index_path = os.path.join(lab_path, "index.md")
        if not os.path.exists(index_path):
            print(f"  skip (no index.md): {lab_folder}")
            continue

        cmds = extract_commands_from_md(index_path, lab_folder)
        if cmds:
            print(f"  {lab_folder}: {len(cmds)} commands extracted")
            all_commands.extend(cmds)
            lab_count += 1
            for c in cmds:
                tool_set.add(c["tool"])
        else:
            print(f"  {lab_folder}: no ```bash blocks found")

    # Deduplicate by command string
    seen = set()
    unique_commands = []
    for cmd in all_commands:
        key = cmd["command"].strip()
        if key not in seen:
            seen.add(key)
            unique_commands.append(cmd)

    print(f"\n── Summary ──────────────────────────")
    print(f"  Labs processed : {lab_count}")
    print(f"  Commands found : {len(unique_commands)}")
    print(f"  Tools detected : {', '.join(sorted(tool_set))}")
    print(f"  Output         : {OUTPUT_JS}")

    # Write JS data file
    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by extract_commands.py — do not edit manually\n")
        f.write("// Run: python3 extract_commands.py\n\n")
        f.write(f"const COMMANDS_DATA = {json.dumps(unique_commands, indent=2)};\n")
        f.write(f"\nconst COMMANDS_META = {json.dumps({'total': len(unique_commands), 'labs': lab_count, 'tools': sorted(list(tool_set))}, indent=2)};\n")

    print(f"\nDone. {len(unique_commands)} commands written to commands-data.js")
    print("Next: copy commands-data.js to your Jekyll root and update commands.html")

if __name__ == "__main__":
    main()
