#!/usr/bin/env python3
"""
btlo_scraper.py
Scrapes the public BTLO profile for inksec and writes assets/js/btlo-stats.js
Consistent with commands-data.js and lab data patterns on inksec.io
"""

import re
import sys
import requests
from pathlib import Path
from datetime import datetime, timezone

PROFILE_URL = "https://blueteamlabs.online/home/user/32e88e341c0c66519ed676"
OUTPUT_PATH = Path("assets/js/btlo-stats.js")

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

# Fallback values — update manually when needed
FALLBACK = {
    "username":         "inksec",
    "rank":             "Junior Defender",
    "points":           "947",
    "global_position":  "606",
    "country_position": "34",
    "investigations":   "24",
    "challenges":       "21",
}


def scrape() -> dict:
    resp = requests.get(PROFILE_URL, headers=HEADERS, timeout=15)
    resp.raise_for_status()
    html = resp.text

    def find(pattern, default="N/A"):
        m = re.search(pattern, html, re.IGNORECASE | re.DOTALL)
        return m.group(1).strip() if m else default

    points         = find(r'(\d+)\s*</span>\s*Points')
    global_pos     = find(r'(\d+)\s*</span>\s*Global\s*Position')
    country_pos    = find(r'(\d+)\s*</span>\s*Country\s*Position')
    investigations = find(r'(\d+)\s*</span>\s*Investigations')
    challenges     = find(r'(\d+)\s*</span>\s*Challenges')
    rank           = find(r'(Junior Defender|Senior Defender|Defender|Rookie|Elite|Master)')

    # If key fields didn't parse fall back
    if points == "N/A" or global_pos == "N/A":
        print("[btlo_scraper] Parse failed — using fallback values")
        return FALLBACK

    return {
        "username":         "inksec",
        "rank":             rank if rank != "N/A" else FALLBACK["rank"],
        "points":           points,
        "global_position":  global_pos,
        "country_position": country_pos,
        "investigations":   investigations,
        "challenges":       challenges,
    }


def write_js(data: dict):
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    js = f"""// Auto-generated by scripts/btlo_scraper.py — do not edit manually
// Last updated: {updated}

const BTLO_STATS = {{
  username:        "{data['username']}",
  rank:            "{data['rank']}",
  points:          "{data['points']}",
  globalPosition:  "{data['global_position']}",
  countryPosition: "{data['country_position']}",
  investigations:  "{data['investigations']}",
  challenges:      "{data['challenges']}",
  updatedAt:       "{updated}",
  profileUrl:      "{PROFILE_URL}"
}};
"""
    OUTPUT_PATH.write_text(js)
    print(f"[btlo_scraper] Written to {OUTPUT_PATH}")
    for k, v in data.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    try:
        data = scrape()
        write_js(data)
    except Exception as e:
        print(f"[btlo_scraper] ERROR: {e}", file=sys.stderr)
        print("[btlo_scraper] Writing fallback values")
        write_js(FALLBACK)
        sys.exit(0)
