#!/usr/bin/env python3
"""
btlo_scraper.py
Scrapes the public BTLO profile for inksec and writes _data/btlo.yml
Run via GitHub Actions on a schedule or manually.
"""

import re
import sys
import requests
from pathlib import Path
from datetime import datetime, timezone

PROFILE_URL = "https://blueteamlabs.online/home/user/32e88e341c0c66519ed676"
OUTPUT_PATH = Path("_data/btlo.yml")

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}


def scrape() -> dict:
    resp = requests.get(PROFILE_URL, headers=HEADERS, timeout=15)
    resp.raise_for_status()
    html = resp.text

    def find(pattern, default="N/A"):
        m = re.search(pattern, html)
        return m.group(1).strip() if m else default

    # Stats visible on the public profile page
    data = {
        "username":         find(r'<h2[^>]*>\s*(inksec)\s*</h2>', "inksec"),
        "rank":             find(r'(?:Junior Defender|Senior Defender|Defender|Rookie|Elite)[^<]*'),
        "points":           find(r'(\d+)\s*</span>\s*Points'),
        "global_position":  find(r'(\d+)\s*</span>\s*Global\s*Position'),
        "country_position": find(r'(\d+)\s*</span>\s*Country\s*Position'),
        "investigations":   find(r'(\d+)\s*</span>\s*Investigations'),
        "challenges":       find(r'(\d+)\s*</span>\s*Challenges'),
        "profile_url":      PROFILE_URL,
        "updated_at":       datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

    return data


def write_yaml(data: dict):
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/btlo_scraper.py — do not edit manually",
        f"# Last updated: {data['updated_at']}",
        "",
    ]
    for key, val in data.items():
        lines.append(f'{key}: "{val}"')
    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"[btlo_scraper] Written to {OUTPUT_PATH}")
    for k, v in data.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    try:
        data = scrape()
        write_yaml(data)
    except Exception as e:
        print(f"[btlo_scraper] ERROR: {e}", file=sys.stderr)
        # Write fallback so Jekyll doesn't break on missing data file
        fallback = {
            "username":         "inksec",
            "rank":             "Junior Defender",
            "points":           "947",
            "global_position":  "606",
            "country_position": "34",
            "investigations":   "24",
            "challenges":       "21",
            "profile_url":      PROFILE_URL,
            "updated_at":       datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }
        write_yaml(fallback)
        sys.exit(0)  # Don't fail the Action on scrape error
