#!/usr/bin/env python3
"""
get_commands.py
Usage: python3 get_commands.py <labname>
Extracts ```bash blocks from a single lab's index.md and appends
new commands to commands-data.js, preserving all existing descriptions.
"""

import os
import re
import json
import sys

# ── CONFIG ──────────────────────────────────────────────────────────────────
LABS_DIR = os.path.expanduser(
    "~/Documents/Obsidian_vault/Hack Academy's Blue Team Obsidian Notes/Cyber_Defenders/LABS"
)
OUTPUT_JS = os.path.expanduser("~/portfolio-v2/blue-team/commands/commands-data.js")

# ── TOOL DETECTION ───────────────────────────────────────────────────────────
TOOL_PATTERNS = [
    ("volatility", [r"\bvol\.py\b", r"\bvol\s+-f\b", r"windows\.\w+", r"volatility"]),
    ("splunk",     [r"\bindex=", r"\bsourcetype=", r"\bstats\s+", r"\btable\s+_time", r"\bdedup\b"]),
    ("zeek",       [r"sourcetype=zeek", r"\bzeek:", r"tx_hosts=", r"id\.orig_h"]),
    ("wireshark",  [r"http\.request", r"http\.response", r"tcp\.stream", r"ip\.src\s*==", r"ip\.dst\s*==", r"ip\.addr\s*==", r"dns\.qry", r"ntlmssp\.", r"smb2\.", r"llmnr", r"tcp\.port"]),
    ("nmap",       [r"\bnmap\b"]),
    ("tshark",     [r"\btshark\b"]),
    ("grep",       [r"^\s*grep\b"]),
]

def detect_tool(command: str) -> str:
    cmd = command.lower()
    for tool, patterns in TOOL_PATTERNS:
        for pattern in patterns:
            if re.search(pattern, cmd):
                return tool
    return "shell"

def load_existing(filepath: str):
    """Load existing commands-data.js, return (list, dict keyed by command string)."""
    if not os.path.exists(filepath):
        return [], {}
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    match = re.search(r"const COMMANDS_DATA = (\[.*?\]);", content, re.DOTALL)
    if not match:
        print("WARNING: Could not parse existing commands-data.js — starting fresh.")
        return [], {}
    try:
        existing_list = json.loads(match.group(1))
        existing_dict = {e["command"].strip(): e for e in existing_list}
        return existing_list, existing_dict
    except json.JSONDecodeError:
        print("WARNING: JSON parse error — starting fresh.")
        return [], {}

def extract_commands(filepath: str, lab_name: str) -> list:
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    pattern = re.compile(r"```bash\s*\n(.*?)```", re.DOTALL)
    blocks = pattern.findall(content)
    commands = []
    for block in blocks:
        lines = block.strip().split("\n")
        tool_override = None
        clean_lines = []
        for line in lines:
            tool_match = re.match(r"#\s*tool:\s*(\w+)", line.strip())
            if tool_match:
                tool_override = tool_match.group(1).lower()
            elif line.strip() and not line.strip().startswith("#"):
                clean_lines.append(line)
        if not clean_lines:
            continue
        full_command = " ".join(l.strip() for l in clean_lines)
        tool = tool_override or detect_tool(full_command)
        commands.append({
            "command": full_command,
            "tool": tool,
            "lab": lab_name,
            "lab_url": f"/blue-team/labs/{lab_name.lower()}/",
            "desc": "",
            "tags": tool,
        })
    return commands

def write_output(filepath: str, commands: list):
    tool_set = sorted(set(c["tool"] for c in commands))
    # Count unique labs
    lab_set = sorted(set(c["lab"] for c in commands))
    meta = {"total": len(commands), "labs": len(lab_set), "tools": tool_set}
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by get_commands.py — do not edit manually\n")
        f.write("// Run: python3 get_commands.py <labname>\n\n")
        f.write(f"const COMMANDS_DATA = {json.dumps(commands, indent=2)};\n")
        f.write(f"\nconst COMMANDS_META = {json.dumps(meta, indent=2)};\n")

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 get_commands.py <labname>")
        print("Example: python3 get_commands.py grabthephisher")
        sys.exit(1)

    lab_arg = sys.argv[1].lower()

    # Find the lab folder (case-insensitive match)
    lab_folder = None
    for folder in os.listdir(LABS_DIR):
        if folder.lower() == lab_arg:
            lab_folder = folder
            break

    if not lab_folder:
        print(f"ERROR: Lab '{lab_arg}' not found in {LABS_DIR}")
        print(f"Available labs: {', '.join(sorted(os.listdir(LABS_DIR)))}")
        sys.exit(1)

    index_path = os.path.join(LABS_DIR, lab_folder, "index.md")
    if not os.path.exists(index_path):
        print(f"ERROR: No index.md found for lab '{lab_folder}'")
        sys.exit(1)

    print(f"Processing lab: {lab_folder}")
    new_cmds = extract_commands(index_path, lab_folder)

    if not new_cmds:
        print("  No ```bash blocks found — nothing to add.")
        sys.exit(0)

    print(f"  Extracted {len(new_cmds)} commands")

    # Load existing and merge
    existing_list, existing_dict = load_existing(OUTPUT_JS)
    print(f"  Existing commands-data.js has {len(existing_list)} commands")

    added = 0
    skipped = 0
    for cmd in new_cmds:
        key = cmd["command"].strip()
        if key in existing_dict:
            skipped += 1
            print(f"  skip (exists): {key[:60]}")
        else:
            existing_list.append(cmd)
            existing_dict[key] = cmd
            added += 1
            print(f"  ++ added: {key[:60]}")

    write_output(OUTPUT_JS, existing_list)

    print(f"\n── Done ─────────────────────────────")
    print(f"  Added   : {added} new commands")
    print(f"  Skipped : {skipped} duplicates")
    print(f"  Total   : {len(existing_list)} commands in commands-data.js")
    if added > 0:
        print(f"\n  Open commands-data.js and fill in 'desc' for the {added} new entries.")

if __name__ == "__main__":
    main()
